using System.Text.Json;
using System.Text;
using ArchiveMail.Api.Mail;
using ArchiveMail.Api.Property;
using ArchiveMail.Api.Security;

namespace ArchiveMail.Api.Endpoints;

public static class PropertyEndpoints
{
    public static IEndpointRouteBuilder MapPropertyEndpoints(this IEndpointRouteBuilder app)
    {
        app.MapGet("/api/auth/property-invitations/preview",async(string? token,PropertyService properties,CancellationToken ct)=>{if(string.IsNullOrWhiteSpace(token))return Results.BadRequest(new{error="Invitation token is required"});try{return Results.Ok(await properties.PreviewInvitation(token,ct));}catch(Exception error){return Error(error);}}).WithTags("Property portal");
        app.MapPost("/api/auth/property-invitations/accept",async(JsonElement input,HttpContext context,PropertyService properties,AuthService auth,CancellationToken ct)=>{try{var preview=await properties.PreviewInvitation(Required(input,"token"),ct);var display=preview.GetType().GetProperty("tenantName")!.GetValue(preview)!.ToString()!;var user=await auth.CreateUserAsync(new(Required(input,"username"),display,"renter",Required(input,"password"),["properties","calendar"]),ct);await properties.AcceptInvitation(Required(input,"token"),user.Id,ct);var result=await auth.LoginAsync(new(Required(input,"username"),Required(input,"password")),AuthService.ClientIp(context),context.Request.Headers.UserAgent.ToString(),ct);context.Response.Cookies.Append("archive_mail_session",result.AccessToken,new CookieOptions{HttpOnly=true,SameSite=SameSiteMode.Strict,Secure=context.Request.IsHttps,Expires=DateTimeOffset.Parse(result.Session.ExpiresAt),Path="/"});return Results.Json(result,statusCode:201);}catch(Exception error){return Error(error);}}).WithTags("Property portal");
        app.MapGet("/api/properties/overview",async(HttpContext context,PropertyService properties,CancellationToken ct)=>Results.Ok(await properties.OverviewAsync(User(context),ct))).WithTags("Properties");
        app.MapGet("/api/property-platform/overview",async(HttpContext context,PropertyService properties,CancellationToken ct)=>Results.Ok(await properties.PlatformOverview(User(context),ct))).WithTags("Properties");
        app.MapPost("/api/properties",async(JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();return await Result(()=>properties.CreateProperty(input,User(context),ct),201);}).WithTags("Properties");
        app.MapPatch("/api/properties/{propertyId}",async(string propertyId,JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();try{return await properties.UpdateProperty(propertyId,input,User(context),ct)is{} value?Results.Ok(value):Results.NotFound(new{error="Property not found"});}catch(Exception error){return Error(error);}}).WithTags("Properties");
        app.MapGet("/api/properties/{propertyId}/photo",async(string propertyId,HttpContext context,PropertyService properties,CancellationToken ct)=>{try{var path=await properties.Photo(propertyId,User(context),ct);return Results.File(path,ContentType(path),enableRangeProcessing:true);}catch(Exception error){return Error(error);}}).WithTags("Properties");
        app.MapPut("/api/properties/{propertyId}/photo",async(string propertyId,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();try{var ext=Extension(context.Request.ContentType);return Results.Ok(await properties.SavePhoto(propertyId,$"photo{ext}",context.Request.Body,User(context),ct));}catch(Exception error){return Error(error);}}).WithTags("Properties");
        app.MapPost("/api/property-tenants",async(JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();return await Result(()=>properties.CreateTenant(input,User(context),ct),201);}).WithTags("Properties");
        app.MapPost("/api/property-leases",async(JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();return await Result(()=>properties.CreateLease(input,User(context),ct),201);}).WithTags("Properties");
        app.MapPost("/api/property-service-requests",(JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>Result(()=>properties.CreateRequest(input,User(context),ct),201)).WithTags("Properties");
        app.MapPatch("/api/property-service-requests/{requestId}",async(string requestId,JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{try{return await properties.UpdateRequest(requestId,input,User(context),ct)is{} value?Results.Ok(value):Results.NotFound(new{error="Service request not found"});}catch(Exception error){return Error(error);}}).WithTags("Properties");
        app.MapPost("/api/property-rent-charges",async(JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();return await Result(()=>properties.CreateCharge(input,User(context),ct),201);}).WithTags("Properties");
        app.MapPost("/api/property-payments",(JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>Result(()=>properties.CreatePayment(input,User(context),ct),201)).WithTags("Properties");
        app.MapPatch("/api/property-payments/{paymentId}",async(string paymentId,JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();try{return await properties.UpdatePayment(paymentId,input,User(context),ct)is{} value?Results.Ok(value):Results.NotFound(new{error="Payment not found"});}catch(Exception error){return Error(error);}}).WithTags("Properties");
        app.MapPost("/api/property-payments/{paymentId}/checkout",(string paymentId,HttpContext context,PropertyPaymentGateway gateway,CancellationToken ct)=>Result(()=>gateway.CheckoutAsync(paymentId,User(context),$"{context.Request.Scheme}://{context.Request.Host}",ct))).WithTags("Properties");
        app.MapPost("/api/property-payments/{paymentId}/sync",async(string paymentId,HttpContext context,PropertyPaymentGateway gateway,CancellationToken ct)=>{try{return Results.Ok(await gateway.SyncAsync(paymentId,User(context),ct));}catch(Exception error){return Error(error);}}).WithTags("Properties");
        app.MapPost("/api/property-payments/{paymentId}/refund",async(string paymentId,JsonElement input,HttpContext context,PropertyPaymentGateway gateway,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();try{var amount=input.TryGetProperty("amountCents",out var value)&&value.TryGetInt64(out var number)?number:(long?)null;return Results.Ok(await gateway.RefundAsync(paymentId,User(context),amount,Required(input,"reason"),ct));}catch(Exception error){return Error(error);}}).WithTags("Properties");
        app.MapPost("/api/property-organizations",async(JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();return await Result(()=>properties.CreateOrganization(input,User(context),ct),201);}).WithTags("Property platform");
        app.MapPost("/api/property-units",async(JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();return await Result(()=>properties.CreateUnit(input,User(context),ct),201);}).WithTags("Property platform");
        app.MapPost("/api/property-tenant-invitations",async(JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();try{var origin=$"{context.Request.Scheme}://{context.Request.Host}";var value=await properties.CreateInvitation(input,User(context),origin,ct);return Results.Json(value.Invitation,statusCode:201);}catch(Exception error){return Error(error);}}).WithTags("Property platform");
        app.MapPost("/api/property-documents",async(string? metadata,string? filename,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();try{using var json=JsonDocument.Parse(metadata??throw new ArgumentException("Document metadata is required"));return Results.Json(await properties.SaveDocument(json.RootElement,filename??"document",context.Request.ContentType??"application/octet-stream",context.Request.Body,User(context),ct),statusCode:201);}catch(Exception error){return Error(error);}}).WithTags("Property documents");
        app.MapPost("/api/property-documents/{documentId}/versions",async(string documentId,string? filename,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();try{return Results.Json(await properties.SaveDocument(JsonSerializer.SerializeToElement(new{}),filename??"document",context.Request.ContentType??"application/octet-stream",context.Request.Body,User(context),ct,documentId),statusCode:201);}catch(Exception error){return Error(error);}}).WithTags("Property documents");
        app.MapGet("/api/property-document-versions/{versionId}/content",async(string versionId,string? disposition,HttpContext context,PropertyService properties,CancellationToken ct)=>{try{var file=await properties.DocumentContent(versionId,User(context),ct);context.Response.Headers.ContentDisposition=$"{(disposition=="inline"?"inline":"attachment")}; filename*=UTF-8''{Uri.EscapeDataString(file.Filename)}";context.Response.Headers.XContentTypeOptions="nosniff";return Results.File(file.Path,file.ContentType,enableRangeProcessing:true);}catch(Exception error){return Error(error);}}).WithTags("Property documents");
        app.MapPost("/api/property-documents/{documentId}/acknowledge",(string documentId,HttpContext context,PropertyService properties,CancellationToken ct)=>Result(()=>properties.Acknowledge(documentId,User(context),ct))).WithTags("Property documents");
        app.MapPost("/api/property-service-requests/{requestId}/comments",(string requestId,JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>Result(()=>properties.AddComment(requestId,input,User(context),ct),201)).WithTags("Property requests");
        app.MapPost("/api/property-service-requests/{requestId}/attachments",(string requestId,string? filename,HttpContext context,PropertyService properties,CancellationToken ct)=>Result(()=>properties.SaveRequestAttachment(requestId,filename??"attachment",context.Request.ContentType??"application/octet-stream",context.Request.Body,User(context),ct),201)).WithTags("Property requests");
        app.MapGet("/api/property-request-attachments/{attachmentId}/content",async(string attachmentId,string? disposition,HttpContext context,PropertyService properties,CancellationToken ct)=>{try{var file=await properties.RequestAttachmentContent(attachmentId,User(context),ct);context.Response.Headers.ContentDisposition=$"{(disposition=="inline"?"inline":"attachment")}; filename*=UTF-8''{Uri.EscapeDataString(file.Filename)}";context.Response.Headers.XContentTypeOptions="nosniff";return Results.File(file.Path,file.ContentType,enableRangeProcessing:true);}catch(Exception error){return Error(error);}}).WithTags("Property requests");
        app.MapPut("/api/property-service-requests/{requestId}/assignment",async(string requestId,JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();try{await properties.AssignRequest(requestId,input,User(context),ct);return Results.NoContent();}catch(Exception error){return Error(error);}}).WithTags("Property requests");
        app.MapPost("/api/property-rent-schedules",async(JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();return await Result(()=>properties.CreateSchedule(input,User(context),ct),201);}).WithTags("Property automation");
        app.MapPost("/api/property-ledger/adjustments",async(JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>{if(!Manager(context))return Results.Forbid();return await Result(()=>properties.Adjustment(input,User(context),ct),201);}).WithTags("Property platform");
        app.MapPut("/api/property-consents",(JsonElement input,HttpContext context,PropertyService properties,CancellationToken ct)=>Result(()=>properties.Consent(input,User(context),ct))).WithTags("Property platform");
        app.MapPatch("/api/admin/property-integrations",(JsonElement input,HttpContext context,PropertyService properties)=>Manager(context)?Results.Ok(properties.UpdateIntegrations(input)):Results.Forbid()).WithTags("Property platform");
        app.MapGet("/api/property-reports/financial.csv",async(HttpContext context,PropertyService properties,CancellationToken ct)=>Manager(context)?Results.Text(await properties.FinancialCsv(User(context),ct),"text/csv",Encoding.UTF8):Results.Forbid()).WithTags("Property reports");
        app.MapPost("/api/property-automation/run",async(HttpContext context,PropertyService properties,CancellationToken ct)=>Manager(context)?Results.Ok(await properties.RunAutomation(User(context),ct)):Results.Forbid()).WithTags("Property automation");
        app.MapGet("/api/admin/property-backups",async(HttpContext context,PropertyService properties,CancellationToken ct)=>Admin(context)?Results.Ok(await properties.Backups(ct)):Results.Forbid()).WithTags("Property backups");
        app.MapPost("/api/admin/property-backups",async(HttpContext context,PropertyService properties,CancellationToken ct)=>Admin(context)?Results.Json(await properties.CreateBackup(ct),statusCode:201):Results.Forbid()).WithTags("Property backups");
        app.MapPost("/api/property-webhooks/stripe",async(HttpContext context,PropertyPaymentGateway gateway,PropertyService properties,CancellationToken ct)=>{try{using var memory=new MemoryStream();await context.Request.Body.CopyToAsync(memory,ct);using var body=gateway.VerifyStripeWebhook(memory.ToArray(),context.Request.Headers["Stripe-Signature"].ToString());var root=body.RootElement;var id=root.TryGetProperty("id",out var value)?value.GetString():null;var type=root.TryGetProperty("type",out value)?value.GetString():null;if(string.IsNullOrWhiteSpace(id)||string.IsNullOrWhiteSpace(type))return Results.BadRequest(new{error="Stripe event ID and type are required"});await properties.RecordProviderEvent("stripe",id,type,root.GetRawText(),ct);await properties.ProcessProviderEventsNow(ct);return Results.Json(new{queued=true},statusCode:202);}catch(Exception error){return Error(error);}}).WithTags("Property webhooks");
        app.MapPost("/api/property-webhooks/paypal",async(HttpContext context,PropertyPaymentGateway gateway,PropertyService properties,CancellationToken ct)=>{try{using var body=await JsonDocument.ParseAsync(context.Request.Body,cancellationToken:ct);await gateway.VerifyPayPalWebhookAsync(context.Request.Headers,body.RootElement,ct);var root=body.RootElement;var id=root.TryGetProperty("id",out var value)?value.GetString():null;var type=root.TryGetProperty("event_type",out value)?value.GetString():null;if(string.IsNullOrWhiteSpace(id)||string.IsNullOrWhiteSpace(type))return Results.BadRequest(new{error="PayPal event ID and type are required"});await properties.RecordProviderEvent("paypal",id,type,root.GetRawText(),ct);await properties.ProcessProviderEventsNow(ct);return Results.Json(new{queued=true},statusCode:202);}catch(Exception error){return Error(error);}}).WithTags("Property webhooks");
        app.MapPost("/api/property-webhooks/twilio/inbound",async(HttpContext context,PropertyPaymentGateway gateway,PropertyService properties,CancellationToken ct)=>{try{var form=await context.Request.ReadFormAsync(ct);var values=form.ToDictionary(item=>item.Key,item=>item.Value.ToString(),StringComparer.Ordinal);var url=$"{context.Request.Scheme}://{context.Request.Host}{context.Request.PathBase}{context.Request.Path}";if(!gateway.VerifyTwilioWebhook(url,values,context.Request.Headers["X-Twilio-Signature"].ToString()))return Results.StatusCode(403);var command=form["Body"].ToString().Trim().ToUpperInvariant();var sender=form["From"].ToString();if(new[]{"STOP","STOPALL","UNSUBSCRIBE","CANCEL","END","QUIT"}.Contains(command)&&!string.IsNullOrWhiteSpace(sender))await properties.RecordSmsOptOut(sender,ct);return Results.Text("<?xml version=\"1.0\" encoding=\"UTF-8\"?><Response></Response>","application/xml",Encoding.UTF8);}catch(Exception error){return Error(error);}}).WithTags("Property webhooks");
        return app;
    }
    private static async Task<IResult> Result(Func<Task<object>> action,int status=200){try{var value=await action();return Results.Json(value,statusCode:status);}catch(Exception error){return Error(error);}}
    private static string User(HttpContext context)=>Session(context).User.Id;private static SessionRecord Session(HttpContext context)=>(SessionRecord)context.Items[AuthService.SessionItemKey]!;private static bool Admin(HttpContext context)=>Session(context).Role=="admin";private static bool Manager(HttpContext context)=>Session(context).Role is "admin" or "user";
    private static IResult Error(Exception error)=>error switch{MailNotFoundException or KeyNotFoundException=>Results.NotFound(new{error=error.Message}),ArgumentException=>Results.BadRequest(new{error=error.Message}),InvalidOperationException=>Results.Conflict(new{error=error.Message}),AuthConflictException=>Results.Conflict(new{error=error.Message}),_=>throw error};
    private static string Required(JsonElement input,string name)=>input.TryGetProperty(name,out var value)&&value.ValueKind==JsonValueKind.String&&!string.IsNullOrWhiteSpace(value.GetString())?value.GetString()!.Trim():throw new ArgumentException($"{name} is required");
    private static string Extension(string? type)=>type?.Split(';')[0].Trim().ToLowerInvariant() switch{"image/png"=>".png","image/webp"=>".webp","image/gif"=>".gif",_=>".jpg"};private static string ContentType(string path)=>Path.GetExtension(path).ToLowerInvariant() switch{".png"=>"image/png",".webp"=>"image/webp",".gif"=>"image/gif",_=>"image/jpeg"};
}

public sealed class PropertyAutomationHostedService(IServiceProvider services,ILogger<PropertyAutomationHostedService> logger):BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken token)
    {
        var interval=int.TryParse(Environment.GetEnvironmentVariable("PROPERTY_AUTOMATION_INTERVAL_MINUTES"),out var minutes)?Math.Max(1,minutes):5;var initial=true;
        while(!token.IsCancellationRequested)
        {
            try
            {
                await Task.Delay(initial?TimeSpan.FromSeconds(1):TimeSpan.FromMinutes(interval),token);initial=false;using var scope=services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<Npgsql.NpgsqlDataSource>();var property=scope.ServiceProvider.GetRequiredService<PropertyService>();await property.ProcessProviderEventsNow(token);
                await using var command=db.CreateCommand("SELECT DISTINCT owner_user_id FROM managed_properties");await using var reader=await command.ExecuteReaderAsync(token);var owners=new List<string>();while(await reader.ReadAsync(token))owners.Add(reader.GetString(0));foreach(var owner in owners)await property.RunAutomation(owner,token);
            }
            catch(OperationCanceledException)when(token.IsCancellationRequested){break;}catch(Exception error){logger.LogError(error,"Property automation cycle failed");}
        }
    }
}
