using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using ArchiveMail.Api.Infrastructure;
using ArchiveMail.Api.Mail;
using ArchiveMail.Api.Gmail;
using Npgsql;

namespace ArchiveMail.Api.Property;

public sealed class PropertyService(NpgsqlDataSource database, ActiveDatabaseConfiguration active, AppSettingsService settings,PropertyPaymentGateway paymentGateway,GmailService gmail,IHttpClientFactory clients)
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);
    private readonly SemaphoreSlim _automationGate=new(1,1);
    public async Task<object> OverviewAsync(string user, CancellationToken token)
    { var owner = await OwnerFor(user, token); var mode = owner == user ? "manager" : "tenant"; var properties = await Properties(owner, user, mode, token); var tenants = await Tenants(owner, user, mode, token); var leases = await Leases(owner, user, mode, token); var requests = await Requests(owner, user, mode, token); var charges = await Charges(owner, user, mode, token); var payments = await Payments(owner, user, mode, token); var month = DateTimeOffset.UtcNow.ToString("yyyy-MM"); return new { mode, generatedAt = DateTimeOffset.UtcNow.ToString("O"), stats = new { propertyCount = properties.Count, occupiedCount = properties.Count(value => Property(value, "status") == "occupied"), openRequestCount = requests.Count(value => Property(value, "status") is not ("completed" or "cancelled")), outstandingBalanceCents = charges.Sum(value => Long(value, "balanceCents")), paidThisMonthCents = payments.Where(value => Property(value, "status") == "succeeded" && Property(value, "paidAt")?.StartsWith(month) == true).Sum(value => Long(value, "amountCents")) }, properties, tenants, leases, serviceRequests = requests, rentCharges = charges, payments, paymentConfiguration = PaymentConfiguration() }; }
    public async Task<object> CreateProperty(JsonElement input, string owner, CancellationToken token) { var id = Guid.NewGuid().ToString(); var now = Now(); var org = await EnsureOrganization(owner, token); const string sql = "INSERT INTO managed_properties(id,owner_user_id,name,address_line1,address_line2,city,state,postal_code,property_type,status,bedrooms,bathrooms,monthly_rent_cents,notes,organization_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$16)"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(owner); command.Parameters.AddWithValue(Required(input, "name")); command.Parameters.AddWithValue(Required(input, "addressLine1")); command.Parameters.AddWithValue(String(input, "addressLine2") ?? ""); command.Parameters.AddWithValue(Required(input, "city")); command.Parameters.AddWithValue(Required(input, "state")); command.Parameters.AddWithValue(Required(input, "postalCode")); command.Parameters.AddWithValue(String(input, "propertyType") ?? "single_family"); command.Parameters.AddWithValue(String(input, "status") ?? "setup"); AddNullable(command, Number(input, "bedrooms")); AddNullable(command, Number(input, "bathrooms")); AddNullable(command, Integer(input, "monthlyRentCents")); command.Parameters.AddWithValue(String(input, "notes") ?? ""); command.Parameters.AddWithValue(org); command.Parameters.AddWithValue(now); await command.ExecuteNonQueryAsync(token); await EnsureUnit(owner, id, token); return (await Properties(owner, owner, "manager", token)).Single(value => Property(value, "id") == id); }
    public async Task<object?> UpdateProperty(string id, JsonElement input, string owner, CancellationToken token) { var columns = new Dictionary<string, string> { { "name", "name" }, { "addressLine1", "address_line1" }, { "addressLine2", "address_line2" }, { "city", "city" }, { "state", "state" }, { "postalCode", "postal_code" }, { "propertyType", "property_type" }, { "status", "status" }, { "bedrooms", "bedrooms" }, { "bathrooms", "bathrooms" }, { "monthlyRentCents", "monthly_rent_cents" }, { "notes", "notes" } }; var set = new List<string>(); var values = new List<object?>(); foreach (var pair in columns) if (input.TryGetProperty(pair.Key, out var value)) { set.Add($"{pair.Value}=${values.Count + 3}"); values.Add(JsonValue(value)); } if (set.Count == 0) throw new ArgumentException("At least one property field is required"); var sql = "UPDATE managed_properties SET " + string.Join(',', set) + ",updated_at=$1 WHERE id=$2 AND owner_user_id=$" + (values.Count + 3); await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(Now()); command.Parameters.AddWithValue(id); foreach (var value in values) command.Parameters.AddWithValue(value ?? DBNull.Value); command.Parameters.AddWithValue(owner); if (await command.ExecuteNonQueryAsync(token) == 0) return null; return (await Properties(owner, owner, "manager", token)).Single(value => Property(value, "id") == id); }
    public async Task<object> SavePhoto(string id, string filename, Stream body, string owner, CancellationToken token) { await EnsureOwnedProperty(id, owner, token); var directory = Path.Combine(active.DataDirectory, "property-photos"); Directory.CreateDirectory(directory); var safe = $"{id}{Path.GetExtension(Path.GetFileName(filename)).ToLowerInvariant()}"; var path = Path.Combine(directory, safe); await using (var output = File.Create(path)) await body.CopyToAsync(output, token); await using var command = database.CreateCommand("UPDATE managed_properties SET image_filename=$2,updated_at=$3 WHERE id=$1"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(safe); command.Parameters.AddWithValue(Now()); await command.ExecuteNonQueryAsync(token); return (await Properties(owner, owner, "manager", token)).Single(value => Property(value, "id") == id); }
    public async Task<string> Photo(string id, string user, CancellationToken token) { await EnsureAccessibleProperty(id, user, token); await using var command = database.CreateCommand("SELECT image_filename FROM managed_properties WHERE id=$1"); command.Parameters.AddWithValue(id); var filename = Convert.ToString(await command.ExecuteScalarAsync(token)); if (string.IsNullOrWhiteSpace(filename)) throw new MailNotFoundException("Property photo not found"); var path = Path.Combine(active.DataDirectory, "property-photos", Path.GetFileName(filename)); if (!File.Exists(path)) throw new MailNotFoundException("Property photo not found"); return path; }
    public async Task<object> CreateTenant(JsonElement input, string owner, CancellationToken token) { var id = Guid.NewGuid().ToString(); var now = Now(); const string sql = "INSERT INTO property_tenants(id,owner_user_id,linked_user_id,first_name,last_name,email,phone,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9)"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(owner); AddNullable(command, String(input, "linkedUserId")); command.Parameters.AddWithValue(Required(input, "firstName")); command.Parameters.AddWithValue(Required(input, "lastName")); command.Parameters.AddWithValue(Required(input, "email").ToLowerInvariant()); command.Parameters.AddWithValue(String(input, "phone") ?? ""); command.Parameters.AddWithValue(String(input, "status") ?? "active"); command.Parameters.AddWithValue(now); await command.ExecuteNonQueryAsync(token); return (await Tenants(owner, owner, "manager", token)).Single(value => Property(value, "id") == id); }
    public async Task<object> CreateLease(JsonElement input, string owner, CancellationToken token) { await EnsureOwnedProperty(Required(input, "propertyId"), owner, token); var id = Guid.NewGuid().ToString(); var now = Now(); const string sql = "INSERT INTO property_leases(id,owner_user_id,property_id,unit_id,tenant_id,start_date,end_date,monthly_rent_cents,security_deposit_cents,due_day,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12)"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(owner); command.Parameters.AddWithValue(Required(input, "propertyId")); AddNullable(command, String(input, "unitId") ?? await EnsureUnit(owner, Required(input, "propertyId"), token)); command.Parameters.AddWithValue(Required(input, "tenantId")); command.Parameters.AddWithValue(Required(input, "startDate")); command.Parameters.AddWithValue(Required(input, "endDate")); command.Parameters.AddWithValue(Integer(input, "monthlyRentCents") ?? throw new ArgumentException("monthlyRentCents is required")); command.Parameters.AddWithValue(Integer(input, "securityDepositCents") ?? 0); command.Parameters.AddWithValue(Integer(input, "dueDay") ?? 1); command.Parameters.AddWithValue(String(input, "status") ?? "active"); command.Parameters.AddWithValue(now); await command.ExecuteNonQueryAsync(token); return (await Leases(owner, owner, "manager", token)).Single(value => Property(value, "id") == id); }
    public async Task<object> CreateRequest(JsonElement input, string user, CancellationToken token) { var owner = await OwnerFor(user, token); await EnsureAccessibleProperty(Required(input, "propertyId"), user, token); var tenant = String(input, "tenantId") ?? (await TenantForUser(user, token)); var id = Guid.NewGuid().ToString(); var now = Now(); const string sql = "INSERT INTO property_service_requests(id,owner_user_id,property_id,tenant_id,title,description,category,priority,status,preferred_entry_at,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'submitted',$9,$10,$10)"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(owner); command.Parameters.AddWithValue(Required(input, "propertyId")); AddNullable(command, tenant); command.Parameters.AddWithValue(Required(input, "title")); command.Parameters.AddWithValue(Required(input, "description")); command.Parameters.AddWithValue(String(input, "category") ?? "General"); command.Parameters.AddWithValue(String(input, "priority") ?? "normal"); AddNullable(command, String(input, "preferredEntryAt")); command.Parameters.AddWithValue(now); await command.ExecuteNonQueryAsync(token); await using var history = database.CreateCommand("INSERT INTO property_request_status_history(id,request_id,to_status,actor_user_id,created_at) VALUES($1,$2,'submitted',$3,$4)"); history.Parameters.AddWithValue(Guid.NewGuid().ToString()); history.Parameters.AddWithValue(id); history.Parameters.AddWithValue(user); history.Parameters.AddWithValue(now); await history.ExecuteNonQueryAsync(token); return (await Requests(owner, user, owner == user ? "manager" : "tenant", token)).Single(value => Property(value, "id") == id); }
    public async Task<object?> UpdateRequest(string id, JsonElement input, string user, CancellationToken token) { var owner = await OwnerFor(user, token); var existing = (await Requests(owner, user, owner == user ? "manager" : "tenant", token)).FirstOrDefault(value => Property(value, "id") == id); if (existing is null) return null; var status = String(input, "status"); await using var command = database.CreateCommand("UPDATE property_service_requests SET priority=COALESCE($2,priority),status=COALESCE($3,status),preferred_entry_at=CASE WHEN $4 THEN $5 ELSE preferred_entry_at END,updated_at=$6 WHERE id=$1"); command.Parameters.AddWithValue(id); AddNullable(command, String(input, "priority")); AddNullable(command, status); command.Parameters.AddWithValue(input.TryGetProperty("preferredEntryAt", out _)); AddNullable(command, String(input, "preferredEntryAt")); command.Parameters.AddWithValue(Now()); await command.ExecuteNonQueryAsync(token); if (status is not null && status != Property(existing, "status")) { await using var history = database.CreateCommand("INSERT INTO property_request_status_history(id,request_id,from_status,to_status,actor_user_id,created_at) VALUES($1,$2,$3,$4,$5,$6)"); history.Parameters.AddWithValue(Guid.NewGuid().ToString()); history.Parameters.AddWithValue(id); history.Parameters.AddWithValue(Property(existing, "status")!); history.Parameters.AddWithValue(status); history.Parameters.AddWithValue(user); history.Parameters.AddWithValue(Now()); await history.ExecuteNonQueryAsync(token); } return (await Requests(owner, user, owner == user ? "manager" : "tenant", token)).Single(value => Property(value, "id") == id); }
    public async Task<object> CreateCharge(JsonElement input, string owner, CancellationToken token) { await EnsureOwnedProperty(Required(input, "propertyId"), owner, token); var id = Guid.NewGuid().ToString(); var now = Now(); const string sql = "INSERT INTO property_rent_charges(id,owner_user_id,property_id,lease_id,description,amount_cents,due_date,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,'open',$8,$8)"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(owner); command.Parameters.AddWithValue(Required(input, "propertyId")); AddNullable(command, String(input, "leaseId")); command.Parameters.AddWithValue(Required(input, "description")); command.Parameters.AddWithValue(Integer(input, "amountCents") ?? throw new ArgumentException("amountCents is required")); command.Parameters.AddWithValue(Required(input, "dueDate")); command.Parameters.AddWithValue(now); await command.ExecuteNonQueryAsync(token); await RecordLedger(owner, Required(input, "propertyId"), String(input, "leaseId"), id, null, "charge", Integer(input, "amountCents")!.Value, Required(input, "description"), now, token); return (await Charges(owner, owner, "manager", token)).Single(value => Property(value, "id") == id); }
    public async Task<object> CreatePayment(JsonElement input, string user, bool isManager, CancellationToken token)
    {
        var owner = await OwnerFor(user, token);
        var propertyId = Required(input, "propertyId");
        await EnsureAccessibleProperty(propertyId, user, token);
        var provider = PropertyPaymentRules.NormalizeProvider(Required(input, "provider"));
        var method = PropertyPaymentRules.NormalizeMethod(String(input, "method") ?? PropertyPaymentRules.DefaultMethod(provider), provider);
        var amount = PropertyPaymentRules.ValidateAmountCents(Integer(input, "amountCents"));
        // A tenant may only ever open a pending payment; declaring one settled is a manager action.
        var status = PropertyPaymentRules.NormalizeCreateStatus(String(input, "status"), isManager);
        var leaseId = String(input, "leaseId");
        var chargeId = String(input, "chargeId");
        if (chargeId is not null) await EnsureChargeMatches(chargeId, propertyId, leaseId, owner, token);
        var id = Guid.NewGuid().ToString();
        var now = Now();
        const string sql = "INSERT INTO property_payments(id,owner_user_id,property_id,lease_id,charge_id,provider,method,amount_cents,currency,status,reference,paid_at,notes,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$14)";
        await using var command = database.CreateCommand(sql);
        command.Parameters.AddWithValue(id);
        command.Parameters.AddWithValue(owner);
        command.Parameters.AddWithValue(propertyId);
        AddNullable(command, leaseId);
        AddNullable(command, chargeId);
        command.Parameters.AddWithValue(provider);
        command.Parameters.AddWithValue(method);
        command.Parameters.AddWithValue(amount);
        command.Parameters.AddWithValue((String(input, "currency") ?? "USD").ToUpperInvariant());
        command.Parameters.AddWithValue(status);
        AddNullable(command, String(input, "reference"));
        // paidAt is only meaningful once settled, and only a manager can create a settled payment.
        AddNullable(command, status == "succeeded" ? (isManager ? String(input, "paidAt") ?? now : now) : null);
        command.Parameters.AddWithValue(String(input, "notes") ?? "");
        command.Parameters.AddWithValue(now);
        await command.ExecuteNonQueryAsync(token);
        if (status == "succeeded") await RecordPayment(id, token);
        return (await Payments(owner, user, owner == user ? "manager" : "tenant", token)).Single(value => Property(value, "id") == id);
    }

    /// <summary>A charge may only be paid by a payment on the same property, and lease when both name one.</summary>
    private async Task EnsureChargeMatches(string chargeId, string propertyId, string? leaseId, string owner, CancellationToken token)
    {
        await using var command = database.CreateCommand(
            "SELECT EXISTS(SELECT 1 FROM property_rent_charges WHERE id=$1 AND property_id=$2 AND owner_user_id=$3 AND ($4::text IS NULL OR lease_id IS NULL OR lease_id=$4))");
        command.Parameters.AddWithValue(chargeId);
        command.Parameters.AddWithValue(propertyId);
        command.Parameters.AddWithValue(owner);
        AddNullable(command, leaseId);
        if (!Convert.ToBoolean(await command.ExecuteScalarAsync(token)))
            throw new ArgumentException("The selected charge does not belong to this property");
    }

    public async Task<object?> UpdatePayment(string id, JsonElement input, string owner, CancellationToken token) { await using var command = database.CreateCommand("UPDATE property_payments SET status=$2,reference=CASE WHEN $3 THEN $4 ELSE reference END,paid_at=CASE WHEN $5='succeeded' THEN COALESCE($6,paid_at,$7) ELSE $6 END,failure_reason=$8,notes=COALESCE($9,notes),updated_at=$7 WHERE id=$1 AND owner_user_id=$10"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(PropertyPaymentRules.NormalizeUpdateStatus(Required(input, "status"))); command.Parameters.AddWithValue(input.TryGetProperty("reference", out _)); AddNullable(command, String(input, "reference")); command.Parameters.AddWithValue(PropertyPaymentRules.NormalizeUpdateStatus(Required(input, "status"))); AddNullable(command, String(input, "paidAt")); command.Parameters.AddWithValue(Now()); AddNullable(command, String(input, "failureReason")); AddNullable(command, String(input, "notes")); command.Parameters.AddWithValue(owner); if (await command.ExecuteNonQueryAsync(token) == 0) return null; if (Required(input, "status") == "succeeded") await RecordPayment(id, token); return (await Payments(owner, owner, "manager", token)).Single(value => Property(value, "id") == id); }
    public async Task<object?> Payment(string id, string user, CancellationToken token) { var owner = await OwnerFor(user, token); return (await Payments(owner, user, owner == user ? "manager" : "tenant", token)).FirstOrDefault(value => Property(value, "id") == id); }

    public async Task<object> PlatformOverview(string user, CancellationToken token) { var owner = await OwnerFor(user, token); return new { organizations = await Organizations(owner, token), memberships = await Memberships(owner, token), units = await Units(owner, user, token), invitations = owner == user ? await Invitations(owner, token) : [], documents = await Documents(owner, user, token), requestComments = await Comments(owner, user, token), requestStatusHistory = await History(owner, user, token), requestAttachments = await Attachments(owner, user, token), rentSchedules = owner == user ? await Schedules(owner, token) : [], ledgerEntries = await Ledger(owner, user, token), receipts = await Receipts(owner, user, token), notificationJobs = owner == user ? await Notifications(owner, token) : [], deliveryAttempts = owner == user ? await Deliveries(owner, token) : [], consents = await Consents(owner, user, token), integrations = IntegrationView(), report = await Report(owner, token) }; }
    public async Task<object> CreateOrganization(JsonElement input, string owner, CancellationToken token) { var id = Guid.NewGuid().ToString(); var now = Now(); await using var tx = await database.OpenConnectionAsync(token); await using var transaction = await tx.BeginTransactionAsync(token); await using (var command = new NpgsqlCommand("INSERT INTO property_organizations(id,owner_user_id,name,timezone,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$5)", tx, transaction)) { command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(owner); command.Parameters.AddWithValue(Required(input, "name")); command.Parameters.AddWithValue(String(input, "timezone") ?? "America/New_York"); command.Parameters.AddWithValue(now); await command.ExecuteNonQueryAsync(token); } await using (var member = new NpgsqlCommand("INSERT INTO property_organization_members(id,organization_id,user_id,role,created_at) VALUES($1,$2,$3,'owner',$4)", tx, transaction)) { member.Parameters.AddWithValue(Guid.NewGuid().ToString()); member.Parameters.AddWithValue(id); member.Parameters.AddWithValue(owner); member.Parameters.AddWithValue(now); await member.ExecuteNonQueryAsync(token); } await transaction.CommitAsync(token); return (await Organizations(owner, token)).Single(value => Property(value, "id") == id); }
    public async Task<object> CreateUnit(JsonElement input, string owner, CancellationToken token) { var property = Required(input, "propertyId"); await EnsureOwnedProperty(property, owner, token); var org = await EnsureOrganization(owner, token); var id = Guid.NewGuid().ToString(); var now = Now(); await using var command = database.CreateCommand("INSERT INTO property_units(id,organization_id,property_id,name,bedrooms,bathrooms,monthly_rent_cents,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9)"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(org); command.Parameters.AddWithValue(property); command.Parameters.AddWithValue(Required(input, "name")); AddNullable(command, Number(input, "bedrooms")); AddNullable(command, Number(input, "bathrooms")); AddNullable(command, Integer(input, "monthlyRentCents")); command.Parameters.AddWithValue(String(input, "status") ?? "available"); command.Parameters.AddWithValue(now); await command.ExecuteNonQueryAsync(token); return (await Units(owner, owner, token)).Single(value => Property(value, "id") == id); }
    public async Task<(object Invitation, string Token)> CreateInvitation(JsonElement input, string owner, string origin, CancellationToken token) { var tenant = Required(input, "tenantId"); var org = await EnsureOrganization(owner, token); await using var check = database.CreateCommand("SELECT email FROM property_tenants WHERE id=$1 AND owner_user_id=$2"); check.Parameters.AddWithValue(tenant); check.Parameters.AddWithValue(owner); var email = Convert.ToString(await check.ExecuteScalarAsync(token)); if(string.IsNullOrWhiteSpace(email))throw new MailNotFoundException("Tenant not found"); var raw = Base64(RandomNumberGenerator.GetBytes(32)); var id = Guid.NewGuid().ToString(); var now = DateTimeOffset.UtcNow; var expires = now.AddHours(Integer(input, "expiresHours") ?? 48).ToString("O"); await using var command = database.CreateCommand("INSERT INTO property_tenant_invitations(id,organization_id,tenant_id,email,token_hash,expires_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(org); command.Parameters.AddWithValue(tenant); command.Parameters.AddWithValue(email); command.Parameters.AddWithValue(Hash(raw)); command.Parameters.AddWithValue(expires); command.Parameters.AddWithValue(now.ToString("O")); await command.ExecuteNonQueryAsync(token); var invitation = (await Invitations(owner, token)).Single(value => Property(value, "id") == id); return (new { id = Property(invitation, "id"), organizationId = Property(invitation, "organizationId"), tenantId = Property(invitation, "tenantId"), tenantName = Property(invitation, "tenantName"), email, expiresAt = expires, acceptedAt = (string?)null, createdAt = now.ToString("O"), invitationUrl = $"{origin}/portal/invite?token={Uri.EscapeDataString(raw)}" }, raw); }
    public async Task<object> PreviewInvitation(string raw, CancellationToken token) { const string sql = "SELECT i.email,i.expires_at,i.accepted_at,t.first_name,t.last_name,o.name FROM property_tenant_invitations i JOIN property_tenants t ON t.id=i.tenant_id JOIN property_organizations o ON o.id=i.organization_id WHERE i.token_hash=$1"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(Hash(raw)); await using var r = await command.ExecuteReaderAsync(token); if (!await r.ReadAsync(token)) throw new MailNotFoundException("Invitation not found"); if (!r.IsDBNull(2)) throw new InvalidOperationException("This invitation has already been accepted"); if (DateTimeOffset.Parse(r.GetString(1)) <= DateTimeOffset.UtcNow) throw new InvalidOperationException("This invitation has expired"); return new { token = raw, tenantName = $"{r.GetString(3)} {r.GetString(4)}".Trim(), email = r.GetString(0), organizationName = r.GetString(5), expiresAt = r.GetString(1) }; }
    public async Task AcceptInvitation(string raw, string user, CancellationToken token)
    {
        await using var connection=await database.OpenConnectionAsync(token);await using var transaction=await connection.BeginTransactionAsync(token);var now=Now();string org;string tenant;
        await using(var command=new NpgsqlCommand("UPDATE property_tenant_invitations i SET accepted_at=$2 FROM property_tenants t WHERE i.token_hash=$1 AND i.accepted_at IS NULL AND i.expires_at::timestamptz>now() AND t.id=i.tenant_id RETURNING i.organization_id,i.tenant_id",connection,transaction)){command.Parameters.AddWithValue(Hash(raw));command.Parameters.AddWithValue(now);await using var reader=await command.ExecuteReaderAsync(token);if(!await reader.ReadAsync(token))throw new InvalidOperationException("Invitation is invalid or expired");org=reader.GetString(0);tenant=reader.GetString(1);}
        await using(var link=new NpgsqlCommand("UPDATE property_tenants SET linked_user_id=$2,updated_at=$3 WHERE id=$1",connection,transaction)){link.Parameters.AddWithValue(tenant);link.Parameters.AddWithValue(user);link.Parameters.AddWithValue(now);await link.ExecuteNonQueryAsync(token);}
        await using(var member=new NpgsqlCommand("INSERT INTO property_organization_members(id,organization_id,user_id,role,created_at) VALUES($1,$2,$3,'tenant',$4) ON CONFLICT(organization_id,user_id) DO NOTHING",connection,transaction)){member.Parameters.AddWithValue(Guid.NewGuid().ToString());member.Parameters.AddWithValue(org);member.Parameters.AddWithValue(user);member.Parameters.AddWithValue(now);await member.ExecuteNonQueryAsync(token);}
        await transaction.CommitAsync(token);
    }

    public async Task<object> AddComment(string request, JsonElement input, string user, CancellationToken token) { await EnsureRequestAccess(request, user, token); var id = Guid.NewGuid().ToString(); var now = Now(); await using var name = database.CreateCommand("SELECT display_name FROM users WHERE id=$1"); name.Parameters.AddWithValue(user); var display = Convert.ToString(await name.ExecuteScalarAsync(token)) ?? "User"; await using var command = database.CreateCommand("INSERT INTO property_request_comments(id,request_id,author_user_id,author_name,body,tenant_visible,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(request); command.Parameters.AddWithValue(user); command.Parameters.AddWithValue(display); command.Parameters.AddWithValue(Required(input, "body")); command.Parameters.AddWithValue(!input.TryGetProperty("tenantVisible", out var visible) || visible.GetBoolean() ? 1 : 0); command.Parameters.AddWithValue(now); await command.ExecuteNonQueryAsync(token); return new { id, requestId = request, authorUserId = user, authorName = display, body = Required(input, "body"), tenantVisible = !input.TryGetProperty("tenantVisible", out visible) || visible.GetBoolean(), createdAt = now }; }
    public async Task AssignRequest(string request, JsonElement input, string owner, CancellationToken token) { await EnsureOwnedRequest(request, owner, token); await using var command = database.CreateCommand("INSERT INTO property_request_assignments(id,request_id,assignee_user_id,target_date,assigned_by_user_id,updated_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(request_id) DO UPDATE SET assignee_user_id=EXCLUDED.assignee_user_id,target_date=EXCLUDED.target_date,assigned_by_user_id=EXCLUDED.assigned_by_user_id,updated_at=EXCLUDED.updated_at"); command.Parameters.AddWithValue(Guid.NewGuid().ToString()); command.Parameters.AddWithValue(request); AddNullable(command, String(input, "assigneeUserId")); AddNullable(command, String(input, "targetDate")); command.Parameters.AddWithValue(owner); command.Parameters.AddWithValue(Now()); await command.ExecuteNonQueryAsync(token); }
    public async Task<object> CreateSchedule(JsonElement input, string owner, CancellationToken token) { var property = Required(input, "propertyId"); await EnsureOwnedProperty(property, owner, token); var org = await EnsureOrganization(owner, token); var id = Guid.NewGuid().ToString(); var now = Now(); await using var command = database.CreateCommand("INSERT INTO property_rent_schedules(id,organization_id,property_id,lease_id,amount_cents,due_day,description_template,next_charge_date,reminder_days_json,enabled,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11)"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(org); command.Parameters.AddWithValue(property); command.Parameters.AddWithValue(Required(input, "leaseId")); command.Parameters.AddWithValue(Integer(input, "amountCents")!.Value); command.Parameters.AddWithValue(Integer(input, "dueDay")!.Value); command.Parameters.AddWithValue(String(input, "descriptionTemplate") ?? "{{month}} rent"); command.Parameters.AddWithValue(Required(input, "nextChargeDate")); command.Parameters.AddWithValue(input.TryGetProperty("reminderDays", out var days) ? days.GetRawText() : "[-7,-3,0,3]"); command.Parameters.AddWithValue(!input.TryGetProperty("enabled", out var enabled) || enabled.GetBoolean() ? 1 : 0); command.Parameters.AddWithValue(now); await command.ExecuteNonQueryAsync(token); return (await Schedules(owner, token)).Single(value => Property(value, "id") == id); }
    public async Task<object> Adjustment(JsonElement input, string owner, CancellationToken token) { var id = await RecordLedger(owner, Required(input, "propertyId"), String(input, "leaseId"), String(input, "chargeId"), null, "adjustment", Integer(input, "amountCents")!.Value, Required(input, "description"), String(input, "effectiveAt") ?? Now(), token); return (await Ledger(owner, owner, token)).Single(value => Property(value, "id") == id); }
    public async Task<object> Consent(JsonElement input, string user, CancellationToken token) { var owner = await OwnerFor(user, token); var tenant = Required(input, "tenantId"); if (owner != user && await TenantForUser(user, token) != tenant) throw new MailNotFoundException("Tenant not found"); var id = Guid.NewGuid().ToString(); var now = Now(); var status = Required(input, "status"); await using var command = database.CreateCommand("INSERT INTO property_communication_consents(id,tenant_id,channel,destination,status,source,consented_at,revoked_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(tenant_id,channel,destination) DO UPDATE SET status=EXCLUDED.status,source=EXCLUDED.source,consented_at=EXCLUDED.consented_at,revoked_at=EXCLUDED.revoked_at,updated_at=EXCLUDED.updated_at RETURNING id"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(tenant); command.Parameters.AddWithValue(Required(input, "channel")); command.Parameters.AddWithValue(Required(input, "destination")); command.Parameters.AddWithValue(status); command.Parameters.AddWithValue(Required(input, "source")); AddNullable(command, status == "opted_in" ? now : null); AddNullable(command, status == "opted_out" ? now : null); command.Parameters.AddWithValue(now); id = Convert.ToString(await command.ExecuteScalarAsync(token))!; return (await Consents(owner, user, token)).Single(value => Property(value, "id") == id); }
    public object UpdateIntegrations(JsonElement input) { settings.UpdatePropertyIntegrations(input); return IntegrationView(); }
    public async Task<string> FinancialCsv(string owner, CancellationToken token) { var rows = await Ledger(owner, owner, token); var builder = new StringBuilder("Date,Type,Property,Description,Amount\n"); foreach (var row in rows) builder.Append(Csv(Property(row, "effectiveAt"))).Append(',').Append(Csv(Property(row, "entryType"))).Append(',').Append(Csv(Property(row, "propertyId"))).Append(',').Append(Csv(Property(row, "description"))).Append(',').Append((Long(row, "amountCents") / 100m).ToString("0.00")).Append('\n'); return builder.ToString(); }
    public async Task<object> RunAutomation(string owner, CancellationToken token)
    {
        var started=Now();if(!await _automationGate.WaitAsync(0,token))return new{startedAt=started,completedAt=Now(),chargesCreated=0,providerEventsProcessed=0,notificationsCompleted=0,notificationsFailed=0,alreadyRunning=true};
        try
        {
            var schedules=await Schedules(owner,token);var created=0;
            foreach(var item in schedules.Where(value=>Property(value,"enabled")=="True"&&string.CompareOrdinal(Property(value,"nextChargeDate"),DateTimeOffset.UtcNow.ToString("yyyy-MM-dd"))<=0))
            {
                var scheduleId=Property(item,"id")!;var chargeDate=Property(item,"nextChargeDate")!;if(!await ClaimScheduleRun(scheduleId,chargeDate,token))continue;
                try
                {
                    var input=JsonSerializer.SerializeToElement(new{propertyId=Property(item,"propertyId"),leaseId=Property(item,"leaseId"),description=Property(item,"descriptionTemplate")!.Replace("{{month}}",DateTimeOffset.UtcNow.ToString("MMMM yyyy")),amountCents=Long(item,"amountCents"),dueDate=chargeDate});
                    var charge=await CreateCharge(input,owner,token);created++;
                    await using var advance=database.CreateCommand("WITH advanced AS (UPDATE property_rent_schedules SET next_charge_date=($2::date+interval '1 month')::date::text,updated_at=$3 WHERE id=$1 RETURNING id) UPDATE property_rent_schedule_runs SET status='completed',charge_id=$4,completed_at=$3,error=NULL WHERE schedule_id=$1 AND charge_date=$2 AND EXISTS(SELECT 1 FROM advanced)");advance.Parameters.AddWithValue(scheduleId);advance.Parameters.AddWithValue(chargeDate);advance.Parameters.AddWithValue(Now());advance.Parameters.AddWithValue(Property(charge,"id")!);await advance.ExecuteNonQueryAsync(token);
                    var reminderDays=item.GetType().GetProperty("reminderDays")?.GetValue(item) as int[]??[];try{await EnqueueChargeReminders(Property(charge,"id")!,reminderDays,token);}catch{/* Charge creation is durable; a later run can repair reminder delivery without duplicating rent. */}
                }
                catch(Exception error){await FailScheduleRun(scheduleId,chargeDate,error.Message,token);}
            }
            var events=await ProcessProviderEvents(token);var notifications=await ProcessNotifications(owner,token);
            return new{startedAt=started,completedAt=Now(),chargesCreated=created,providerEventsProcessed=events,notificationsCompleted=notifications.Completed,notificationsFailed=notifications.Failed,alreadyRunning=false};
        }
        finally{_automationGate.Release();}
    }
    private async Task<bool> ClaimScheduleRun(string schedule,string chargeDate,CancellationToken token)
    {await using var command=database.CreateCommand("INSERT INTO property_rent_schedule_runs(id,schedule_id,charge_date,status,created_at) VALUES($1,$2,$3,'running',$4) ON CONFLICT(schedule_id,charge_date) DO NOTHING");command.Parameters.AddWithValue(Guid.NewGuid().ToString());command.Parameters.AddWithValue(schedule);command.Parameters.AddWithValue(chargeDate);command.Parameters.AddWithValue(Now());return await command.ExecuteNonQueryAsync(token)==1;}
    private async Task FailScheduleRun(string schedule,string chargeDate,string error,CancellationToken token)
    {await using var command=database.CreateCommand("UPDATE property_rent_schedule_runs SET status='failed',error=$3,completed_at=$4 WHERE schedule_id=$1 AND charge_date=$2");command.Parameters.AddWithValue(schedule);command.Parameters.AddWithValue(chargeDate);command.Parameters.AddWithValue(error);command.Parameters.AddWithValue(Now());await command.ExecuteNonQueryAsync(token);}
    private async Task<int> ProcessProviderEvents(CancellationToken token)
    {
        var completed=0;
        for(var count=0;count<100;count++)
        {
            await using var claim=database.CreateCommand("WITH candidate AS (SELECT id FROM property_provider_events WHERE status='queued' ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE property_provider_events e SET status='running',attempts=e.attempts+1 FROM candidate WHERE e.id=candidate.id RETURNING e.id,e.provider,e.event_type,e.payload_json,e.attempts");
            await using var reader=await claim.ExecuteReaderAsync(token);if(!await reader.ReadAsync(token))break;var id=reader.GetString(0);var provider=reader.GetString(1);var eventType=reader.GetString(2);var payload=reader.GetString(3);var attempts=reader.GetInt64(4);await reader.CloseAsync();
            try{await paymentGateway.ApplyProviderEventAsync(provider,eventType,payload,token);await SetProviderEventStatus(id,"completed",null,true,token);completed++;}
            catch(Exception error){await SetProviderEventStatus(id,attempts>=5?"failed":"queued",error.Message,attempts>=5,token);}
        }
        return completed;
    }
    public Task<int> ProcessProviderEventsNow(CancellationToken token)=>ProcessProviderEvents(token);
    private async Task SetProviderEventStatus(string id,string status,string? error,bool terminal,CancellationToken token)
    {await using var command=database.CreateCommand("UPDATE property_provider_events SET status=$2,last_error=$3,processed_at=CASE WHEN $4 THEN $5 ELSE NULL END WHERE id=$1");command.Parameters.AddWithValue(id);command.Parameters.AddWithValue(status);AddNullable(command,error);command.Parameters.AddWithValue(terminal);command.Parameters.AddWithValue(Now());await command.ExecuteNonQueryAsync(token);}
    private async Task<(int Completed,int Failed)> ProcessNotifications(string owner,CancellationToken token)
    {
        var completed=0;var failed=0;
        for(var count=0;count<100;count++)
        {
            const string sql="WITH candidate AS (SELECT n.id FROM property_notification_jobs n JOIN property_organizations o ON o.id=n.organization_id WHERE o.owner_user_id=$1 AND n.status='queued' AND n.scheduled_at::timestamptz<=now() AND n.next_attempt_at::timestamptz<=now() ORDER BY n.scheduled_at,n.created_at FOR UPDATE OF n SKIP LOCKED LIMIT 1) UPDATE property_notification_jobs n SET status='running',attempts=n.attempts+1 FROM candidate WHERE n.id=candidate.id RETURNING n.id,n.tenant_id,n.channel,n.recipient,n.subject,n.body,n.attempts,n.max_attempts";
            await using var claim=database.CreateCommand(sql);claim.Parameters.AddWithValue(owner);await using var reader=await claim.ExecuteReaderAsync(token);if(!await reader.ReadAsync(token))break;var id=reader.GetString(0);var tenant=reader.IsDBNull(1)?null:reader.GetString(1);var channel=reader.GetString(2);var recipient=reader.GetString(3);var subject=reader.GetString(4);var body=reader.GetString(5);var attempts=reader.GetInt64(6);var maxAttempts=reader.GetInt64(7);await reader.CloseAsync();
            try
            {
                string provider;string? providerId=null;string deliveryStatus="succeeded";string? deliveryError=null;
                if(channel=="in_app")provider="local";
                else if(channel=="email")
                {var connection=settings.Current().PropertyIntegrationsValue.GmailConnectionId;if(string.IsNullOrWhiteSpace(connection))throw new InvalidOperationException("Gmail reminder account is not configured");var sent=await gmail.SendAsync(connection,owner,JsonSerializer.SerializeToElement(new{to=new[]{recipient},cc=Array.Empty<string>(),bcc=Array.Empty<string>(),subject,bodyText=body}),token);provider="gmail";providerId=Property(sent,"id");}
                else if(!await CanSendSms(tenant,recipient,token)){provider="consent";deliveryStatus="suppressed";deliveryError="SMS consent is not active";}
                else{provider="twilio";providerId=await SendSms(recipient,body,token);}
                await CompleteNotification(id,provider,providerId,deliveryStatus,deliveryError,token);completed++;
            }
            catch(Exception error){await FailNotification(id,attempts,maxAttempts,error.Message,token);failed++;}
        }
        return(completed,failed);
    }
    private async Task EnqueueChargeReminders(string chargeId,int[] reminderDays,CancellationToken token)
    {
        const string sql="SELECT c.due_date,c.description,c.amount_cents,p.organization_id,p.name,t.id,t.linked_user_id,t.first_name,t.email,t.phone FROM property_rent_charges c JOIN managed_properties p ON p.id=c.property_id LEFT JOIN property_leases l ON l.id=c.lease_id LEFT JOIN property_tenants t ON t.id=l.tenant_id WHERE c.id=$1";
        await using var command=database.CreateCommand(sql);command.Parameters.AddWithValue(chargeId);await using var reader=await command.ExecuteReaderAsync(token);if(!await reader.ReadAsync(token)||reader.IsDBNull(5))return;var due=DateOnly.Parse(reader.GetString(0));var description=reader.GetString(1);var amount=reader.GetInt64(2);var org=reader.GetString(3);var property=reader.GetString(4);var tenant=reader.GetString(5);var linked=reader.IsDBNull(6)?null:reader.GetString(6);var first=reader.GetString(7);var email=reader.GetString(8);var phone=reader.GetString(9);await reader.CloseAsync();
        foreach(var offset in reminderDays.Distinct())
        {var scheduled=due.AddDays(offset).ToDateTime(new TimeOnly(9,0),DateTimeKind.Utc).ToString("O");var timing=offset<0?$"due in {Math.Abs(offset)} day{(Math.Abs(offset)==1?"":"s")}":offset==0?"due today":$"{offset} day{(offset==1?"":"s")} overdue";var subject=$"Rent reminder: {property} is {timing}";var body=$"Hello {first},\n\n{description} for {property} is {timing}. Amount: {(amount/100m):C}. Due date: {due:yyyy-MM-dd}.\n\nPlease use the tenant portal to review your balance or payment options.";if(linked is not null)await EnqueueNotification(org,tenant,chargeId,"in_app",linked,subject,body,scheduled,$"rent-reminder:{chargeId}:{offset}:in_app",token);if(!string.IsNullOrWhiteSpace(email))await EnqueueNotification(org,tenant,chargeId,"email",email,subject,body,scheduled,$"rent-reminder:{chargeId}:{offset}:email",token);if(!string.IsNullOrWhiteSpace(phone)&&await CanSendSms(tenant,phone,token))await EnqueueNotification(org,tenant,chargeId,"sms",phone,subject,body,scheduled,$"rent-reminder:{chargeId}:{offset}:sms",token);}
    }
    private async Task EnqueueNotification(string org,string tenant,string charge,string channel,string recipient,string subject,string body,string scheduled,string key,CancellationToken token)
    {await using var command=database.CreateCommand("INSERT INTO property_notification_jobs(id,organization_id,tenant_id,charge_id,channel,recipient,subject,body,scheduled_at,status,attempts,max_attempts,next_attempt_at,idempotency_key,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'queued',0,5,$9,$10,$11) ON CONFLICT(idempotency_key) DO NOTHING");command.Parameters.AddWithValue(Guid.NewGuid().ToString());command.Parameters.AddWithValue(org);command.Parameters.AddWithValue(tenant);command.Parameters.AddWithValue(charge);command.Parameters.AddWithValue(channel);command.Parameters.AddWithValue(recipient);command.Parameters.AddWithValue(subject);command.Parameters.AddWithValue(body);command.Parameters.AddWithValue(scheduled);command.Parameters.AddWithValue(key);command.Parameters.AddWithValue(Now());await command.ExecuteNonQueryAsync(token);}
    private async Task<bool> CanSendSms(string? tenant,string recipient,CancellationToken token)
    {if(tenant is null)return false;await using var command=database.CreateCommand("SELECT EXISTS(SELECT 1 FROM property_communication_consents WHERE tenant_id=$1 AND channel='sms' AND destination=$2 AND status='opted_in')");command.Parameters.AddWithValue(tenant);command.Parameters.AddWithValue(recipient);return Convert.ToBoolean(await command.ExecuteScalarAsync(token));}
    private async Task<string> SendSms(string recipient,string body,CancellationToken token)
    {var config=settings.Current().PropertyIntegrationsValue;if(string.IsNullOrWhiteSpace(config.TwilioAccountSid)||string.IsNullOrWhiteSpace(config.TwilioAuthToken)||string.IsNullOrWhiteSpace(config.TwilioMessagingServiceSid))throw new InvalidOperationException("Twilio SMS is not configured");using var request=new HttpRequestMessage(HttpMethod.Post,$"https://api.twilio.com/2010-04-01/Accounts/{Uri.EscapeDataString(config.TwilioAccountSid)}/Messages.json"){Content=new FormUrlEncodedContent(new Dictionary<string,string>{{"To",recipient},{"MessagingServiceSid",config.TwilioMessagingServiceSid},{"Body",body}})};request.Headers.Authorization=new("Basic",Convert.ToBase64String(Encoding.UTF8.GetBytes($"{config.TwilioAccountSid}:{config.TwilioAuthToken}")));using var response=await clients.CreateClient("external").SendAsync(request,token);var payload=await response.Content.ReadAsStringAsync(token);using var json=JsonDocument.Parse(string.IsNullOrWhiteSpace(payload)?"{}":payload);if(!response.IsSuccessStatusCode)throw new InvalidOperationException(json.RootElement.TryGetProperty("message",out var message)?message.GetString():$"Twilio SMS failed ({(int)response.StatusCode})");return json.RootElement.TryGetProperty("sid",out var sid)?sid.GetString()??throw new InvalidOperationException("Twilio did not return a message ID"):throw new InvalidOperationException("Twilio did not return a message ID");}
    private async Task CompleteNotification(string id,string provider,string? providerId,string status,string? error,CancellationToken token)
    {var now=Now();await using var command=database.CreateCommand("WITH delivery AS (INSERT INTO property_delivery_attempts(id,job_id,provider,provider_id,status,error,created_at) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING job_id) UPDATE property_notification_jobs SET status='completed',completed_at=$7,last_error=$6 WHERE id=$2 AND EXISTS(SELECT 1 FROM delivery)");command.Parameters.AddWithValue(Guid.NewGuid().ToString());command.Parameters.AddWithValue(id);command.Parameters.AddWithValue(provider);AddNullable(command,providerId);command.Parameters.AddWithValue(status);AddNullable(command,error);command.Parameters.AddWithValue(now);await command.ExecuteNonQueryAsync(token);}
    private async Task FailNotification(string id,long attempts,long maxAttempts,string error,CancellationToken token)
    {var terminal=attempts>=maxAttempts;var next=DateTimeOffset.UtcNow.AddMinutes(Math.Min(60,Math.Pow(2,attempts))).ToString("O");var now=Now();await using var command=database.CreateCommand("WITH delivery AS (INSERT INTO property_delivery_attempts(id,job_id,provider,status,error,created_at) VALUES($1,$2,'system','failed',$3,$4) RETURNING job_id) UPDATE property_notification_jobs SET status=$5,next_attempt_at=$6,last_error=$3,completed_at=CASE WHEN $7 THEN $4 ELSE NULL END WHERE id=$2 AND EXISTS(SELECT 1 FROM delivery)");command.Parameters.AddWithValue(Guid.NewGuid().ToString());command.Parameters.AddWithValue(id);command.Parameters.AddWithValue(error);command.Parameters.AddWithValue(now);command.Parameters.AddWithValue(terminal?"failed":"queued");command.Parameters.AddWithValue(next);command.Parameters.AddWithValue(terminal);await command.ExecuteNonQueryAsync(token);}
    public async Task RecordProviderEvent(string provider, string eventId, string eventType, string payload, CancellationToken token) { await using var command = database.CreateCommand("INSERT INTO property_provider_events(id,provider,event_id,event_type,payload_json,status,attempts,created_at) VALUES($1,$2,$3,$4,$5,'queued',0,$6) ON CONFLICT(provider,event_id) DO NOTHING"); command.Parameters.AddWithValue(Guid.NewGuid().ToString()); command.Parameters.AddWithValue(provider); command.Parameters.AddWithValue(eventId); command.Parameters.AddWithValue(eventType); command.Parameters.AddWithValue(payload); command.Parameters.AddWithValue(Now()); await command.ExecuteNonQueryAsync(token); }
    public async Task RecordSmsOptOut(string sender,CancellationToken token){await using var command=database.CreateCommand("UPDATE property_communication_consents SET status='opted_out',revoked_at=$2,updated_at=$2 WHERE channel='sms' AND destination=$1");command.Parameters.AddWithValue(sender);command.Parameters.AddWithValue(Now());await command.ExecuteNonQueryAsync(token);}
    public Task<IReadOnlyList<object>> Backups(CancellationToken token)
    {
        var root=Path.Combine(active.DataDirectory,"backups");Directory.CreateDirectory(root);token.ThrowIfCancellationRequested();var result=new List<object>();
        foreach(var path in Directory.EnumerateDirectories(root,"property-*")){var databaseFile=Path.Combine(path,"database.dump");var totals=TreeSize(path);var info=new DirectoryInfo(path);result.Add(new{id=info.Name,createdAt=info.CreationTimeUtc.ToString("O"),sizeBytes=totals.Bytes,databaseBytes=File.Exists(databaseFile)?new FileInfo(databaseFile).Length:0,fileCount=totals.Files});}
        foreach(var path in Directory.EnumerateFiles(root,"property-*.dump")){var file=new FileInfo(path);result.Add(new{id=Path.GetFileNameWithoutExtension(path),createdAt=file.CreationTimeUtc.ToString("O"),sizeBytes=file.Length,databaseBytes=file.Length,fileCount=1});}
        return Task.FromResult<IReadOnlyList<object>>(result.OrderByDescending(value=>Property(value,"createdAt")).ToArray());
    }
    public async Task<object> CreateBackup(CancellationToken token)
    {
        var root=Path.Combine(active.DataDirectory,"backups");Directory.CreateDirectory(root);var id=$"property-{DateTime.UtcNow:yyyyMMdd-HHmmss}";var destination=Path.Combine(root,id);Directory.CreateDirectory(destination);var databasePath=Path.Combine(destination,"database.dump");
        var postgres=new NpgsqlConnectionStringBuilder(active.ConnectionString);var info=new System.Diagnostics.ProcessStartInfo("pg_dump"){RedirectStandardError=true,UseShellExecute=false};info.ArgumentList.Add("--format=custom");info.ArgumentList.Add($"--file={databasePath}");info.ArgumentList.Add($"--host={postgres.Host}");info.ArgumentList.Add($"--port={postgres.Port}");info.ArgumentList.Add($"--username={postgres.Username}");info.ArgumentList.Add($"--dbname={postgres.Database}");info.Environment["PGPASSWORD"]=postgres.Password;using var process=System.Diagnostics.Process.Start(info)??throw new InvalidOperationException("pg_dump could not start");await process.WaitForExitAsync(token);if(process.ExitCode!=0){Directory.Delete(destination,true);throw new InvalidOperationException($"PostgreSQL backup failed: {await process.StandardError.ReadToEndAsync(token)}");}
        foreach(var folder in new[]{"property-files","property-photos","data-protection-keys"}){var source=Path.Combine(active.DataDirectory,folder);if(Directory.Exists(source))CopyDirectory(source,Path.Combine(destination,folder),token);}
        var settingsPath=Path.Combine(active.DataDirectory,"app-settings.protected.json");if(File.Exists(settingsPath))File.Copy(settingsPath,Path.Combine(destination,Path.GetFileName(settingsPath)),true);
        await File.WriteAllTextAsync(Path.Combine(destination,"manifest.json"),JsonSerializer.Serialize(new{id,createdAt=Now(),databaseFilename="database.dump",restore="Stop Archive Mail, restore database.dump with pg_restore, restore the bundled files, then restart."},new JsonSerializerOptions(JsonOptions){WriteIndented=true}),token);
        var retention=int.TryParse(Environment.GetEnvironmentVariable("PROPERTY_BACKUP_RETENTION"),out var configured)?Math.Max(1,configured):7;foreach(var old in Directory.EnumerateDirectories(root,"property-*").OrderByDescending(path=>path,StringComparer.Ordinal).Skip(retention))Directory.Delete(old,true);
        var totals=TreeSize(destination);return new{id,createdAt=new DirectoryInfo(destination).CreationTimeUtc.ToString("O"),sizeBytes=totals.Bytes,databaseBytes=new FileInfo(databasePath).Length,fileCount=totals.Files};
    }

    public async Task<object> SaveDocument(JsonElement metadata, string filename, string contentType, Stream body, string user, CancellationToken token, string? documentId = null) { var owner = await OwnerFor(user, token); var directory = Path.Combine(active.DataDirectory, "property-files"); Directory.CreateDirectory(directory); var versionId = Guid.NewGuid().ToString(); var temp = Path.Combine(directory, $"{versionId}.tmp"); await using (var output = File.Create(temp)) await body.CopyToAsync(output, token); var bytes = new FileInfo(temp).Length; string sha; await using(var input=File.OpenRead(temp))sha=Convert.ToHexString(await SHA256.HashDataAsync(input, token)).ToLowerInvariant(); var key = $"property-files/{sha}"; var final = Path.Combine(active.DataDirectory, key); if (File.Exists(final)) File.Delete(temp); else File.Move(temp, final); var now = Now(); if (documentId is null) { documentId = Guid.NewGuid().ToString(); var property = Required(metadata, "propertyId"); await EnsureOwnedProperty(property, owner, token); var org = await EnsureOrganization(owner, token); await using var document = database.CreateCommand("INSERT INTO property_documents(id,organization_id,property_id,lease_id,tenant_id,title,category,visibility,requires_acknowledgement,created_by_user_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11)"); document.Parameters.AddWithValue(documentId); document.Parameters.AddWithValue(org); document.Parameters.AddWithValue(property); AddNullable(document, String(metadata, "leaseId")); AddNullable(document, String(metadata, "tenantId")); document.Parameters.AddWithValue(Required(metadata, "title")); document.Parameters.AddWithValue(String(metadata, "category") ?? "Agreement"); document.Parameters.AddWithValue(String(metadata, "visibility") ?? "tenant"); document.Parameters.AddWithValue(Boolean(metadata, "requiresAcknowledgement") ? 1 : 0); document.Parameters.AddWithValue(user); document.Parameters.AddWithValue(now); await document.ExecuteNonQueryAsync(token); } else await EnsureDocumentOwner(documentId, owner, token); await using var version = database.CreateCommand("INSERT INTO property_document_versions(id,document_id,version,filename,content_type,size_bytes,sha256,storage_key,created_by_user_id,created_at) SELECT $1,$2,COALESCE(MAX(version),0)+1,$3,$4,$5,$6,$7,$8,$9 FROM property_document_versions WHERE document_id=$2"); version.Parameters.AddWithValue(versionId); version.Parameters.AddWithValue(documentId); version.Parameters.AddWithValue(Path.GetFileName(filename)); version.Parameters.AddWithValue(contentType); version.Parameters.AddWithValue(bytes); version.Parameters.AddWithValue(sha); version.Parameters.AddWithValue(key); version.Parameters.AddWithValue(user); version.Parameters.AddWithValue(now); await version.ExecuteNonQueryAsync(token); return (await Documents(owner, user, token)).Single(value => Property(value, "id") == documentId); }
    public async Task<object> Acknowledge(string document, string user, CancellationToken token) { var owner = await OwnerFor(user, token); if (!(await Documents(owner, user, token)).Any(value => Property(value, "id") == document)) throw new MailNotFoundException("Document not found"); var now = Now(); await using var command = database.CreateCommand("INSERT INTO property_document_acknowledgements(id,document_id,user_id,acknowledged_at) VALUES($1,$2,$3,$4) ON CONFLICT(document_id,user_id) DO UPDATE SET acknowledged_at=EXCLUDED.acknowledged_at"); command.Parameters.AddWithValue(Guid.NewGuid().ToString()); command.Parameters.AddWithValue(document); command.Parameters.AddWithValue(user); command.Parameters.AddWithValue(now); await command.ExecuteNonQueryAsync(token); return (await Documents(owner, user, token)).Single(value => Property(value, "id") == document); }
    public async Task<(string Filename, string ContentType, string Path)> DocumentContent(string version, string user, CancellationToken token) { var owner = await OwnerFor(user, token); const string sql = "SELECT v.filename,v.content_type,v.storage_key FROM property_document_versions v JOIN property_documents d ON d.id=v.document_id JOIN managed_properties p ON p.id=d.property_id WHERE v.id=$1 AND p.owner_user_id=$2"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(version); command.Parameters.AddWithValue(owner); await using var r = await command.ExecuteReaderAsync(token); if (!await r.ReadAsync(token)) throw new MailNotFoundException("Document version not found"); return (r.GetString(0), r.GetString(1), Path.Combine(active.DataDirectory, r.GetString(2))); }
    public async Task<object> SaveRequestAttachment(string request, string filename, string contentType, Stream body, string user, CancellationToken token) { await EnsureRequestAccess(request, user, token); var directory = Path.Combine(active.DataDirectory, "property-files"); Directory.CreateDirectory(directory); var id = Guid.NewGuid().ToString(); var temp = Path.Combine(directory, $"{id}.tmp"); await using (var output = File.Create(temp)) await body.CopyToAsync(output, token); var bytes = new FileInfo(temp).Length; string sha; await using(var input=File.OpenRead(temp))sha=Convert.ToHexString(await SHA256.HashDataAsync(input, token)).ToLowerInvariant(); var key = $"property-files/{sha}"; var final = Path.Combine(active.DataDirectory, key); if (File.Exists(final)) File.Delete(temp); else File.Move(temp, final); var now = Now(); await using var command = database.CreateCommand("INSERT INTO property_request_attachments(id,request_id,uploaded_by_user_id,filename,content_type,size_bytes,sha256,storage_key,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(request); command.Parameters.AddWithValue(user); command.Parameters.AddWithValue(Path.GetFileName(filename)); command.Parameters.AddWithValue(contentType); command.Parameters.AddWithValue(bytes); command.Parameters.AddWithValue(sha); command.Parameters.AddWithValue(key); command.Parameters.AddWithValue(now); await command.ExecuteNonQueryAsync(token); return new { id, requestId = request, filename = Path.GetFileName(filename), contentType, sizeBytes = bytes, sha256 = sha, createdAt = now }; }
    public async Task<(string Filename, string ContentType, string Path)> RequestAttachmentContent(string id, string user, CancellationToken token) { var owner = await OwnerFor(user, token); const string sql = "SELECT a.filename,a.content_type,a.storage_key FROM property_request_attachments a JOIN property_service_requests r ON r.id=a.request_id WHERE a.id=$1 AND r.owner_user_id=$2"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(owner); await using var r = await command.ExecuteReaderAsync(token); if (!await r.ReadAsync(token)) throw new MailNotFoundException("Attachment not found"); return (r.GetString(0), r.GetString(1), Path.Combine(active.DataDirectory, r.GetString(2))); }

    private async Task<List<object>> Properties(string owner, string user, string mode, CancellationToken token) { var tenant = mode == "tenant" ? await TenantForUser(user, token) : null; const string sql = "SELECT p.id,p.name,p.address_line1,p.address_line2,p.city,p.state,p.postal_code,p.property_type,p.status,p.image_filename,p.bedrooms,p.bathrooms,p.monthly_rent_cents,p.notes,p.created_at,p.updated_at,(SELECT t.first_name||' '||t.last_name FROM property_leases l JOIN property_tenants t ON t.id=l.tenant_id WHERE l.property_id=p.id AND l.status='active' LIMIT 1),(SELECT l.end_date FROM property_leases l WHERE l.property_id=p.id AND l.status='active' LIMIT 1),(SELECT COUNT(*) FROM property_service_requests r WHERE r.property_id=p.id AND r.status NOT IN ('completed','cancelled')),(SELECT COALESCE(SUM(c.amount_cents-COALESCE((SELECT SUM(pay.amount_cents) FROM property_payments pay WHERE pay.charge_id=c.id AND pay.status='succeeded'),0)),0) FROM property_rent_charges c WHERE c.property_id=p.id) FROM managed_properties p WHERE p.owner_user_id=$1 AND ($2::text IS NULL OR EXISTS(SELECT 1 FROM property_leases l WHERE l.property_id=p.id AND l.tenant_id=$2)) ORDER BY lower(p.name)"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(owner); AddNullable(command, tenant); await using var r = await command.ExecuteReaderAsync(token); var list = new List<object>(); while (await r.ReadAsync(token)) list.Add(new { id = r.GetString(0), name = r.GetString(1), addressLine1 = r.GetString(2), addressLine2 = r.GetString(3), city = r.GetString(4), state = r.GetString(5), postalCode = r.GetString(6), propertyType = r.GetString(7), status = r.GetString(8), imageUrl = r.IsDBNull(9) ? null : $"/api/properties/{r.GetString(0)}/photo", bedrooms = r.IsDBNull(10) ? (double?)null : r.GetDouble(10), bathrooms = r.IsDBNull(11) ? (double?)null : r.GetDouble(11), monthlyRentCents = r.IsDBNull(12) ? (long?)null : r.GetInt64(12), tenantName = r.IsDBNull(16) ? null : r.GetString(16), leaseEndDate = r.IsDBNull(17) ? null : r.GetString(17), openRequestCount = r.GetInt64(18), outstandingBalanceCents = r.GetInt64(19), notes = r.GetString(13), createdAt = r.GetString(14), updatedAt = r.GetString(15) }); return list; }
    private async Task<List<object>> Tenants(string owner, string user, string mode, CancellationToken token) { var tenant = mode == "tenant" ? await TenantForUser(user, token) : null; await using var command = database.CreateCommand("SELECT id,linked_user_id,first_name,last_name,email,phone,status,created_at,updated_at FROM property_tenants WHERE owner_user_id=$1 AND ($2::text IS NULL OR id=$2) ORDER BY lower(last_name),lower(first_name)"); command.Parameters.AddWithValue(owner); AddNullable(command, tenant); await using var r = await command.ExecuteReaderAsync(token); var list = new List<object>(); while (await r.ReadAsync(token)) list.Add(new { id = r.GetString(0), linkedUserId = r.IsDBNull(1) ? null : r.GetString(1), firstName = r.GetString(2), lastName = r.GetString(3), displayName = $"{r.GetString(2)} {r.GetString(3)}", email = r.GetString(4), phone = r.GetString(5), status = r.GetString(6), createdAt = r.GetString(7), updatedAt = r.GetString(8) }); return list; }
    private async Task<List<object>> Leases(string owner, string user, string mode, CancellationToken token) { var tenant = mode == "tenant" ? await TenantForUser(user, token) : null; const string sql = "SELECT l.id,l.property_id,l.unit_id,l.tenant_id,t.first_name||' '||t.last_name,p.name,l.start_date,l.end_date,l.monthly_rent_cents,l.security_deposit_cents,l.due_day,l.status,l.created_at,l.updated_at FROM property_leases l JOIN property_tenants t ON t.id=l.tenant_id JOIN managed_properties p ON p.id=l.property_id WHERE l.owner_user_id=$1 AND ($2::text IS NULL OR l.tenant_id=$2) ORDER BY l.end_date DESC"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(owner); AddNullable(command, tenant); await using var r = await command.ExecuteReaderAsync(token); var list = new List<object>(); while (await r.ReadAsync(token)) list.Add(new { id = r.GetString(0), propertyId = r.GetString(1), unitId = r.IsDBNull(2) ? null : r.GetString(2), tenantId = r.GetString(3), tenantName = r.GetString(4), propertyName = r.GetString(5), startDate = r.GetString(6), endDate = r.GetString(7), monthlyRentCents = r.GetInt64(8), securityDepositCents = r.GetInt64(9), dueDay = r.GetInt64(10), status = r.GetString(11), createdAt = r.GetString(12), updatedAt = r.GetString(13) }); return list; }
    private async Task<List<object>> Requests(string owner, string user, string mode, CancellationToken token) { var tenant = mode == "tenant" ? await TenantForUser(user, token) : null; const string sql = "SELECT r.id,r.property_id,r.tenant_id,p.name,t.first_name||' '||t.last_name,r.title,r.description,r.category,r.priority,r.status,r.preferred_entry_at,r.created_at,r.updated_at FROM property_service_requests r JOIN managed_properties p ON p.id=r.property_id LEFT JOIN property_tenants t ON t.id=r.tenant_id WHERE r.owner_user_id=$1 AND ($2::text IS NULL OR r.tenant_id=$2) ORDER BY r.updated_at DESC"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(owner); AddNullable(command, tenant); await using var r = await command.ExecuteReaderAsync(token); var list = new List<object>(); while (await r.ReadAsync(token)) list.Add(new { id = r.GetString(0), propertyId = r.GetString(1), tenantId = r.IsDBNull(2) ? null : r.GetString(2), propertyName = r.GetString(3), tenantName = r.IsDBNull(4) ? null : r.GetString(4), title = r.GetString(5), description = r.GetString(6), category = r.GetString(7), priority = r.GetString(8), status = r.GetString(9), preferredEntryAt = r.IsDBNull(10) ? null : r.GetString(10), createdAt = r.GetString(11), updatedAt = r.GetString(12) }); return list; }
    private async Task<List<object>> Charges(string owner, string user, string mode, CancellationToken token) { var tenant = mode == "tenant" ? await TenantForUser(user, token) : null; const string sql = "SELECT c.id,c.property_id,c.lease_id,p.name,c.description,c.amount_cents,COALESCE((SELECT SUM(pay.amount_cents) FROM property_payments pay WHERE pay.charge_id=c.id AND pay.status='succeeded'),0),c.due_date,c.status,c.created_at,c.updated_at FROM property_rent_charges c JOIN managed_properties p ON p.id=c.property_id LEFT JOIN property_leases l ON l.id=c.lease_id WHERE c.owner_user_id=$1 AND ($2::text IS NULL OR l.tenant_id=$2) ORDER BY c.due_date DESC"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(owner); AddNullable(command, tenant); await using var r = await command.ExecuteReaderAsync(token); var list = new List<object>(); while (await r.ReadAsync(token)) { var amount = r.GetInt64(5); var paid = r.GetInt64(6); list.Add(new { id = r.GetString(0), propertyId = r.GetString(1), leaseId = r.IsDBNull(2) ? null : r.GetString(2), propertyName = r.GetString(3), description = r.GetString(4), amountCents = amount, paidCents = paid, balanceCents = Math.Max(0, amount - paid), dueDate = r.GetString(7), status = paid >= amount ? "paid" : r.GetString(8), createdAt = r.GetString(9), updatedAt = r.GetString(10) }); } return list; }
    private async Task<List<object>> Payments(string owner, string user, string mode, CancellationToken token) { var tenant = mode == "tenant" ? await TenantForUser(user, token) : null; const string sql = "SELECT x.id,x.property_id,x.lease_id,x.charge_id,p.name,x.provider,x.method,x.amount_cents,x.currency,x.status,x.external_id,x.provider_transaction_id,x.checkout_url,x.reference,x.paid_at,x.failure_reason,x.notes,x.created_at,x.updated_at FROM property_payments x JOIN managed_properties p ON p.id=x.property_id LEFT JOIN property_leases l ON l.id=x.lease_id WHERE x.owner_user_id=$1 AND ($2::text IS NULL OR l.tenant_id=$2) ORDER BY x.created_at DESC"; await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(owner); AddNullable(command, tenant); await using var r = await command.ExecuteReaderAsync(token); var list = new List<object>(); while (await r.ReadAsync(token)) list.Add(new { id = r.GetString(0), propertyId = r.GetString(1), leaseId = r.IsDBNull(2) ? null : r.GetString(2), chargeId = r.IsDBNull(3) ? null : r.GetString(3), propertyName = r.GetString(4), provider = r.GetString(5), method = r.GetString(6), amountCents = r.GetInt64(7), currency = r.GetString(8), status = r.GetString(9), externalId = r.IsDBNull(10) ? null : r.GetString(10), providerTransactionId = r.IsDBNull(11) ? null : r.GetString(11), checkoutUrl = r.IsDBNull(12) ? null : r.GetString(12), reference = r.IsDBNull(13) ? null : r.GetString(13), paidAt = r.IsDBNull(14) ? null : r.GetString(14), failureReason = r.IsDBNull(15) ? null : r.GetString(15), notes = r.GetString(16), createdAt = r.GetString(17), updatedAt = r.GetString(18) }); return list; }

    // Platform projections intentionally remain direct PostgreSQL queries so migrated rows retain their original identifiers.
    private Task<List<object>> Organizations(string owner, CancellationToken token) => Rows("SELECT id,name,owner_user_id,timezone,created_at,updated_at FROM property_organizations WHERE owner_user_id=$1", [owner], r => new { id = r.GetString(0), name = r.GetString(1), ownerUserId = r.GetString(2), timezone = r.GetString(3), createdAt = r.GetString(4), updatedAt = r.GetString(5) }, token);
    private Task<List<object>> Memberships(string owner, CancellationToken token) => Rows("SELECT m.id,m.organization_id,m.user_id,u.display_name,m.role,m.created_at FROM property_organization_members m JOIN property_organizations o ON o.id=m.organization_id JOIN users u ON u.id=m.user_id WHERE o.owner_user_id=$1", [owner], r => new { id = r.GetString(0), organizationId = r.GetString(1), userId = r.GetString(2), displayName = r.GetString(3), role = r.GetString(4), createdAt = r.GetString(5) }, token);
    private async Task<List<object>> Units(string owner, string user, CancellationToken token) { var tenant = await TenantForUser(user, token); return await Rows("SELECT u.id,u.organization_id,u.property_id,p.name,u.name,u.bedrooms,u.bathrooms,u.monthly_rent_cents,u.status,u.created_at,u.updated_at FROM property_units u JOIN managed_properties p ON p.id=u.property_id WHERE p.owner_user_id=$1 AND ($2::text IS NULL OR EXISTS(SELECT 1 FROM property_leases l WHERE l.unit_id=u.id AND l.tenant_id=$2))", [owner, tenant], r => new { id = r.GetString(0), organizationId = r.GetString(1), propertyId = r.GetString(2), propertyName = r.GetString(3), name = r.GetString(4), bedrooms = r.IsDBNull(5) ? (double?)null : r.GetDouble(5), bathrooms = r.IsDBNull(6) ? (double?)null : r.GetDouble(6), monthlyRentCents = r.IsDBNull(7) ? (long?)null : r.GetInt64(7), status = r.GetString(8), createdAt = r.GetString(9), updatedAt = r.GetString(10) }, token); }
    private Task<List<object>> Invitations(string owner, CancellationToken token) => Rows("SELECT i.id,i.organization_id,i.tenant_id,t.first_name||' '||t.last_name,i.email,i.expires_at,i.accepted_at,i.created_at FROM property_tenant_invitations i JOIN property_organizations o ON o.id=i.organization_id JOIN property_tenants t ON t.id=i.tenant_id WHERE o.owner_user_id=$1 ORDER BY i.created_at DESC", [owner], r => new { id = r.GetString(0), organizationId = r.GetString(1), tenantId = r.GetString(2), tenantName = r.GetString(3), email = r.GetString(4), expiresAt = r.GetString(5), acceptedAt = r.IsDBNull(6) ? null : r.GetString(6), createdAt = r.GetString(7), invitationUrl = (string?)null }, token);
    private async Task<List<object>> Documents(string owner, string user, CancellationToken token) => await Rows("SELECT d.id,d.organization_id,d.property_id,p.name,d.lease_id,d.tenant_id,d.title,d.category,d.visibility,d.requires_acknowledgement<>0,ack.acknowledged_at,v.id,v.version,v.filename,v.content_type,v.size_bytes,v.sha256,v.created_at,d.created_at,d.updated_at FROM property_documents d JOIN managed_properties p ON p.id=d.property_id JOIN LATERAL(SELECT * FROM property_document_versions WHERE document_id=d.id ORDER BY version DESC LIMIT 1)v ON true LEFT JOIN property_document_acknowledgements ack ON ack.document_id=d.id AND ack.user_id=$2 WHERE p.owner_user_id=$1 AND ($1=$2 OR d.visibility='tenant')", [owner, user], r => new { id = r.GetString(0), organizationId = r.GetString(1), propertyId = r.GetString(2), propertyName = r.GetString(3), leaseId = r.IsDBNull(4) ? null : r.GetString(4), tenantId = r.IsDBNull(5) ? null : r.GetString(5), title = r.GetString(6), category = r.GetString(7), visibility = r.GetString(8), requiresAcknowledgement = r.GetBoolean(9), acknowledgedAt = r.IsDBNull(10) ? null : r.GetString(10), latestVersion = new { id = r.GetString(11), documentId = r.GetString(0), version = r.GetInt64(12), filename = r.GetString(13), contentType = r.GetString(14), sizeBytes = r.GetInt64(15), sha256 = r.GetString(16), createdAt = r.GetString(17) }, createdAt = r.GetString(18), updatedAt = r.GetString(19) }, token);
    private Task<List<object>> Comments(string owner, string user, CancellationToken token) => Rows("SELECT c.id,c.request_id,c.author_user_id,c.author_name,c.body,c.tenant_visible<>0,c.created_at FROM property_request_comments c JOIN property_service_requests r ON r.id=c.request_id WHERE r.owner_user_id=$1 AND ($1=$2 OR c.tenant_visible<>0)", [owner, user], r => new { id = r.GetString(0), requestId = r.GetString(1), authorUserId = r.GetString(2), authorName = r.GetString(3), body = r.GetString(4), tenantVisible = r.GetBoolean(5), createdAt = r.GetString(6) }, token);
    private Task<List<object>> History(string owner, string user, CancellationToken token) => Rows("SELECT h.id,h.request_id,h.from_status,h.to_status,h.actor_user_id,h.created_at FROM property_request_status_history h JOIN property_service_requests r ON r.id=h.request_id WHERE r.owner_user_id=$1", [owner], r => new { id = r.GetString(0), requestId = r.GetString(1), fromStatus = r.IsDBNull(2) ? null : r.GetString(2), toStatus = r.GetString(3), actorUserId = r.GetString(4), createdAt = r.GetString(5) }, token);
    private Task<List<object>> Attachments(string owner, string user, CancellationToken token) => Rows("SELECT a.id,a.request_id,a.filename,a.content_type,a.size_bytes,a.sha256,a.created_at FROM property_request_attachments a JOIN property_service_requests r ON r.id=a.request_id WHERE r.owner_user_id=$1", [owner], r => new { id = r.GetString(0), requestId = r.GetString(1), filename = r.GetString(2), contentType = r.GetString(3), sizeBytes = r.GetInt64(4), sha256 = r.GetString(5), createdAt = r.GetString(6) }, token);
    private Task<List<object>> Schedules(string owner, CancellationToken token) => Rows("SELECT s.id,s.organization_id,s.property_id,p.name,s.lease_id,s.amount_cents,s.due_day,s.description_template,s.next_charge_date,s.reminder_days_json,s.enabled<>0,s.created_at,s.updated_at FROM property_rent_schedules s JOIN managed_properties p ON p.id=s.property_id WHERE p.owner_user_id=$1", [owner], r => new { id = r.GetString(0), organizationId = r.GetString(1), propertyId = r.GetString(2), propertyName = r.GetString(3), leaseId = r.GetString(4), amountCents = r.GetInt64(5), dueDay = r.GetInt64(6), descriptionTemplate = r.GetString(7), nextChargeDate = r.GetString(8), reminderDays = ParseInts(r.GetString(9)), enabled = r.GetBoolean(10), createdAt = r.GetString(11), updatedAt = r.GetString(12) }, token);
    private Task<List<object>> Ledger(string owner, string user, CancellationToken token) => Rows("SELECT l.id,l.organization_id,l.property_id,l.lease_id,l.charge_id,l.payment_id,l.entry_type,l.amount_cents,l.description,l.effective_at,l.created_at FROM property_ledger_entries l JOIN managed_properties p ON p.id=l.property_id WHERE p.owner_user_id=$1 ORDER BY l.effective_at DESC", [owner], r => new { id = r.GetString(0), organizationId = r.GetString(1), propertyId = r.GetString(2), leaseId = r.IsDBNull(3) ? null : r.GetString(3), chargeId = r.IsDBNull(4) ? null : r.GetString(4), paymentId = r.IsDBNull(5) ? null : r.GetString(5), entryType = r.GetString(6), amountCents = r.GetInt64(7), description = r.GetString(8), effectiveAt = r.GetString(9), createdAt = r.GetString(10) }, token);
    private Task<List<object>> Receipts(string owner, string user, CancellationToken token) => Rows("SELECT r.id,r.payment_id,r.receipt_number,r.amount_cents,r.currency,r.paid_at,r.created_at FROM property_receipts r JOIN property_payments p ON p.id=r.payment_id WHERE p.owner_user_id=$1", [owner], r => new { id = r.GetString(0), paymentId = r.GetString(1), receiptNumber = r.GetString(2), amountCents = r.GetInt64(3), currency = r.GetString(4), paidAt = r.GetString(5), createdAt = r.GetString(6) }, token);
    private Task<List<object>> Notifications(string owner, CancellationToken token) => Rows("SELECT n.id,n.organization_id,n.tenant_id,n.charge_id,n.channel,n.recipient,n.subject,n.body,n.scheduled_at,n.status,n.attempts,n.last_error,n.completed_at,n.created_at FROM property_notification_jobs n JOIN property_organizations o ON o.id=n.organization_id WHERE o.owner_user_id=$1", [owner], r => new { id = r.GetString(0), organizationId = r.GetString(1), tenantId = r.IsDBNull(2) ? null : r.GetString(2), chargeId = r.IsDBNull(3) ? null : r.GetString(3), channel = r.GetString(4), recipient = r.GetString(5), subject = r.GetString(6), body = r.GetString(7), scheduledAt = r.GetString(8), status = r.GetString(9), attempts = r.GetInt64(10), lastError = r.IsDBNull(11) ? null : r.GetString(11), completedAt = r.IsDBNull(12) ? null : r.GetString(12), createdAt = r.GetString(13) }, token);
    private Task<List<object>> Deliveries(string owner, CancellationToken token) => Rows("SELECT d.id,d.job_id,d.provider,d.provider_id,d.status,d.error,d.created_at FROM property_delivery_attempts d JOIN property_notification_jobs n ON n.id=d.job_id JOIN property_organizations o ON o.id=n.organization_id WHERE o.owner_user_id=$1", [owner], r => new { id = r.GetString(0), jobId = r.GetString(1), provider = r.GetString(2), providerId = r.IsDBNull(3) ? null : r.GetString(3), status = r.GetString(4), error = r.IsDBNull(5) ? null : r.GetString(5), createdAt = r.GetString(6) }, token);
    private async Task<List<object>> Consents(string owner, string user, CancellationToken token) => await Rows("SELECT c.id,c.tenant_id,c.channel,c.destination,c.status,c.source,c.consented_at,c.revoked_at,c.updated_at FROM property_communication_consents c JOIN property_tenants t ON t.id=c.tenant_id WHERE t.owner_user_id=$1 AND ($1=$2 OR t.linked_user_id=$2)", [owner, user], r => new { id = r.GetString(0), tenantId = r.GetString(1), channel = r.GetString(2), destination = r.GetString(3), status = r.GetString(4), source = r.GetString(5), consentedAt = r.IsDBNull(6) ? null : r.GetString(6), revokedAt = r.IsDBNull(7) ? null : r.GetString(7), updatedAt = r.GetString(8) }, token);
    private async Task<object> Report(string owner, CancellationToken token) { var values = await ScalarRow("SELECT COALESCE((SELECT SUM(amount_cents) FROM property_ledger_entries l JOIN property_organizations o ON o.id=l.organization_id WHERE o.owner_user_id=$1 AND entry_type='charge'),0),COALESCE((SELECT SUM(amount_cents) FROM property_ledger_entries l JOIN property_organizations o ON o.id=l.organization_id WHERE o.owner_user_id=$1 AND entry_type='payment'),0),COALESCE((SELECT SUM(amount_cents) FROM property_ledger_entries l JOIN property_organizations o ON o.id=l.organization_id WHERE o.owner_user_id=$1 AND entry_type='adjustment'),0),(SELECT COUNT(*) FROM property_rent_charges WHERE owner_user_id=$1 AND status='overdue'),(SELECT COUNT(*) FROM property_service_requests WHERE owner_user_id=$1 AND status NOT IN('completed','cancelled')),(SELECT COUNT(*) FROM property_leases WHERE owner_user_id=$1 AND status='active' AND end_date::date<=current_date+interval '60 days'),(SELECT COUNT(*) FROM property_notification_jobs n JOIN property_organizations o ON o.id=n.organization_id WHERE o.owner_user_id=$1 AND n.status='queued')", owner, token); return new { generatedAt = Now(), totalChargesCents = values[0], totalPaymentsCents = values[1], totalAdjustmentsCents = values[2], outstandingCents = Math.Max(0, values[0] - values[1] + values[2]), overdueCharges = values[3], openRequests = values[4], expiringLeases = values[5], queuedNotifications = values[6] }; }
    private object PaymentConfiguration() { var value = settings.Current().PropertyIntegrationsValue; return new { stripe = new { configured = value.StripeSecretKey.Length > 0, methods = new[] { "card", "apple_pay", "google_pay", "ach" } }, paypal = new { configured = value.PaypalClientId.Length > 0 && value.PaypalClientSecret.Length > 0, environment = value.PaypalEnvironment, methods = new[] { "paypal" } }, zelle = new { configured = value.ZelleRecipient is not null, recipient = value.ZelleRecipient, note = value.ZelleNote }, appleCash = new { configured = value.AppleCashRecipient is not null, recipient = value.AppleCashRecipient, note = value.AppleCashNote }, manual = new { configured = true, methods = new[] { "cash", "check", "bank_transfer", "other" } } }; }
    private object IntegrationView() { var value = settings.Current().PropertyIntegrationsValue; return new { stripeConfigured = value.StripeSecretKey.Length > 0, stripeSource = value.StripeSecretKey.Length > 0 ? "admin" : "none", stripeWebhookConfigured = value.StripeWebhookSecret.Length > 0, paypalConfigured = value.PaypalClientId.Length > 0 && value.PaypalClientSecret.Length > 0, paypalSource = value.PaypalClientSecret.Length > 0 ? "admin" : "none", paypalEnvironment = value.PaypalEnvironment, paypalWebhookConfigured = value.PaypalWebhookId.Length > 0, zelleRecipient = value.ZelleRecipient, appleCashRecipient = value.AppleCashRecipient, appleCashNote = value.AppleCashNote, twilioConfigured = value.TwilioAccountSid.Length > 0 && value.TwilioAuthToken.Length > 0, twilioSource = value.TwilioAuthToken.Length > 0 ? "admin" : "none", gmailConnectionId = value.GmailConnectionId }; }
    private async Task<string> EnsureOrganization(string owner, CancellationToken token) { await using var get = database.CreateCommand("SELECT id FROM property_organizations WHERE owner_user_id=$1 ORDER BY created_at LIMIT 1"); get.Parameters.AddWithValue(owner); if (Convert.ToString(await get.ExecuteScalarAsync(token)) is { Length: > 0 } id) return id; var input = JsonSerializer.SerializeToElement(new { name = "Property Management", timezone = "America/New_York" }); var created = await CreateOrganization(input, owner, token); return Property(created, "id")!; }
    private async Task<string> EnsureUnit(string owner, string property, CancellationToken token) { await using var get = database.CreateCommand("SELECT id FROM property_units WHERE property_id=$1 ORDER BY created_at LIMIT 1"); get.Parameters.AddWithValue(property); if (Convert.ToString(await get.ExecuteScalarAsync(token)) is { Length: > 0 } id) return id; await using var row = database.CreateCommand("SELECT name,bedrooms,bathrooms,monthly_rent_cents,status FROM managed_properties WHERE id=$1 AND owner_user_id=$2"); row.Parameters.AddWithValue(property); row.Parameters.AddWithValue(owner); await using var r = await row.ExecuteReaderAsync(token); if (!await r.ReadAsync(token)) throw new MailNotFoundException("Property not found"); var input = JsonSerializer.SerializeToElement(new { propertyId = property, name = "Main unit", bedrooms = r.IsDBNull(1) ? null : (double?)r.GetDouble(1), bathrooms = r.IsDBNull(2) ? null : (double?)r.GetDouble(2), monthlyRentCents = r.IsDBNull(3) ? null : (long?)r.GetInt64(3), status = r.GetString(4) == "occupied" ? "occupied" : "available" }); await r.CloseAsync(); var unit = await CreateUnit(input, owner, token); return Property(unit, "id")!; }
    private async Task<string> OwnerFor(string user, CancellationToken token) { await using var command = database.CreateCommand("SELECT owner_user_id FROM managed_properties WHERE owner_user_id=$1 UNION ALL SELECT owner_user_id FROM property_tenants WHERE linked_user_id=$1 LIMIT 1"); command.Parameters.AddWithValue(user); var owner = Convert.ToString(await command.ExecuteScalarAsync(token)); return string.IsNullOrWhiteSpace(owner) ? user : owner; }
    private async Task<string?> TenantForUser(string user, CancellationToken token)
    {
        await using var command = database.CreateCommand("SELECT id FROM property_tenants WHERE linked_user_id=$1 LIMIT 1");
        command.Parameters.AddWithValue(user);
        var tenant = Convert.ToString(await command.ExecuteScalarAsync(token));
        return string.IsNullOrWhiteSpace(tenant) ? null : tenant;
    }
    private async Task EnsureOwnedProperty(string id, string owner, CancellationToken token) { await using var command = database.CreateCommand("SELECT EXISTS(SELECT 1 FROM managed_properties WHERE id=$1 AND owner_user_id=$2)"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(owner); if (!Convert.ToBoolean(await command.ExecuteScalarAsync(token))) throw new MailNotFoundException("Property not found"); }
    private async Task EnsureAccessibleProperty(string id, string user, CancellationToken token) { var owner = await OwnerFor(user, token); if (owner == user) { await EnsureOwnedProperty(id, owner, token); return; } var tenant = await TenantForUser(user, token); await using var command = database.CreateCommand("SELECT EXISTS(SELECT 1 FROM property_leases WHERE property_id=$1 AND tenant_id=$2)"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(tenant ?? ""); if (!Convert.ToBoolean(await command.ExecuteScalarAsync(token))) throw new MailNotFoundException("Property not found"); }
    private async Task EnsureOwnedRequest(string id, string owner, CancellationToken token) { await using var command = database.CreateCommand("SELECT EXISTS(SELECT 1 FROM property_service_requests WHERE id=$1 AND owner_user_id=$2)"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(owner); if (!Convert.ToBoolean(await command.ExecuteScalarAsync(token))) throw new MailNotFoundException("Service request not found"); }
    private async Task EnsureRequestAccess(string id, string user, CancellationToken token) { var owner = await OwnerFor(user, token); if (owner == user) { await EnsureOwnedRequest(id, owner, token); return; } var tenant = await TenantForUser(user, token); await using var command = database.CreateCommand("SELECT EXISTS(SELECT 1 FROM property_service_requests WHERE id=$1 AND owner_user_id=$2 AND tenant_id=$3)"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(owner); command.Parameters.AddWithValue(tenant ?? ""); if (!Convert.ToBoolean(await command.ExecuteScalarAsync(token))) throw new MailNotFoundException("Service request not found"); }
    private async Task EnsureDocumentOwner(string id, string owner, CancellationToken token) { await using var command = database.CreateCommand("SELECT EXISTS(SELECT 1 FROM property_documents d JOIN managed_properties p ON p.id=d.property_id WHERE d.id=$1 AND p.owner_user_id=$2)"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(owner); if (!Convert.ToBoolean(await command.ExecuteScalarAsync(token))) throw new MailNotFoundException("Document not found"); }
    private async Task<string> RecordLedger(string owner, string property, string? lease, string? charge, string? payment, string type, long amount, string description, string effective, CancellationToken token) { await EnsureOwnedProperty(property, owner, token); var org = await EnsureOrganization(owner, token); var id = Guid.NewGuid().ToString(); await using var command = database.CreateCommand("INSERT INTO property_ledger_entries(id,organization_id,property_id,lease_id,charge_id,payment_id,entry_type,amount_cents,description,effective_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)"); command.Parameters.AddWithValue(id); command.Parameters.AddWithValue(org); command.Parameters.AddWithValue(property); AddNullable(command, lease); AddNullable(command, charge); AddNullable(command, payment); command.Parameters.AddWithValue(type); command.Parameters.AddWithValue(amount); command.Parameters.AddWithValue(description); command.Parameters.AddWithValue(effective); command.Parameters.AddWithValue(Now()); await command.ExecuteNonQueryAsync(token); return id; }
    private async Task RecordPayment(string id, CancellationToken token) { await using var command = database.CreateCommand("SELECT owner_user_id,property_id,lease_id,charge_id,amount_cents,currency,paid_at FROM property_payments WHERE id=$1"); command.Parameters.AddWithValue(id); await using var r = await command.ExecuteReaderAsync(token); await r.ReadAsync(token); var owner = r.GetString(0); var property = r.GetString(1); var lease = r.IsDBNull(2) ? null : r.GetString(2); var charge = r.IsDBNull(3) ? null : r.GetString(3); var amount = r.GetInt64(4); var currency = r.GetString(5); var paid = r.IsDBNull(6) ? Now() : r.GetString(6); await r.CloseAsync(); if (await Exists("SELECT EXISTS(SELECT 1 FROM property_ledger_entries WHERE payment_id=$1 AND entry_type='payment')", id, token)) return; await RecordLedger(owner, property, lease, charge, id, "payment", amount, "Rent payment", paid, token); await using var receipt = database.CreateCommand("INSERT INTO property_receipts(id,payment_id,receipt_number,amount_cents,currency,paid_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(payment_id) DO NOTHING"); receipt.Parameters.AddWithValue(Guid.NewGuid().ToString()); receipt.Parameters.AddWithValue(id); receipt.Parameters.AddWithValue($"AM-{DateTime.UtcNow:yyyyMMdd}-{id[..8].ToUpperInvariant()}"); receipt.Parameters.AddWithValue(amount); receipt.Parameters.AddWithValue(currency); receipt.Parameters.AddWithValue(paid); receipt.Parameters.AddWithValue(Now()); await receipt.ExecuteNonQueryAsync(token); }
    private async Task<bool> Exists(string sql, string id, CancellationToken token) { await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(id); return Convert.ToBoolean(await command.ExecuteScalarAsync(token)); }
    private async Task<List<object>> Rows(string sql, object?[] parameters, Func<NpgsqlDataReader, object> map, CancellationToken token) { await using var command = database.CreateCommand(sql); foreach (var value in parameters) command.Parameters.AddWithValue(value ?? DBNull.Value); await using var r = await command.ExecuteReaderAsync(token); var list = new List<object>(); while (await r.ReadAsync(token)) list.Add(map(r)); return list; }
    private async Task<long[]> ScalarRow(string sql, string owner, CancellationToken token) { await using var command = database.CreateCommand(sql); command.Parameters.AddWithValue(owner); await using var r = await command.ExecuteReaderAsync(token); await r.ReadAsync(token); return Enumerable.Range(0, r.FieldCount).Select(r.GetInt64).ToArray(); }
    private static object? JsonValue(JsonElement value) => value.ValueKind switch { JsonValueKind.String => value.GetString(), JsonValueKind.Number when value.TryGetInt64(out var integer) => integer, JsonValueKind.Number => value.GetDouble(), JsonValueKind.True => true, JsonValueKind.False => false, JsonValueKind.Null => null, _ => value.GetRawText() };
    private static string? Property(object value, string name) => value.GetType().GetProperty(name)?.GetValue(value)?.ToString();
    private static long Long(object value, string name) => Convert.ToInt64(value.GetType().GetProperty(name)?.GetValue(value) ?? 0);
    private static string Required(JsonElement input, string name) => String(input, name) ?? throw new ArgumentException($"{name} is required");
    private static string? String(JsonElement input, string name) => input.ValueKind == JsonValueKind.Object && input.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.String ? value.GetString()?.Trim() : null;
    private static long? Integer(JsonElement input, string name) => input.ValueKind == JsonValueKind.Object && input.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.Number && value.TryGetInt64(out var number) ? number : null;
    private static double? Number(JsonElement input, string name) => input.ValueKind == JsonValueKind.Object && input.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.Number && value.TryGetDouble(out var number) ? number : null;
    private static bool Boolean(JsonElement input, string name) => input.ValueKind == JsonValueKind.Object && input.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.True;
    private static void AddNullable(NpgsqlCommand command, object? value) => command.Parameters.AddWithValue(value ?? DBNull.Value);
    private static string Now() => DateTimeOffset.UtcNow.ToString("O");
    private static string Hash(string value) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
    private static string Base64(byte[] value) => Convert.ToBase64String(value).TrimEnd('=').Replace('+', '-').Replace('/', '_');
    private static int[] ParseInts(string json) { try { return JsonSerializer.Deserialize<int[]>(json, JsonOptions) ?? []; } catch { return []; } }
    private static string Csv(string? value) => $"\"{(value ?? "").Replace("\"", "\"\"")}\"";
    private static void CopyDirectory(string source,string destination,CancellationToken token){Directory.CreateDirectory(destination);foreach(var file in Directory.EnumerateFiles(source)){token.ThrowIfCancellationRequested();File.Copy(file,Path.Combine(destination,Path.GetFileName(file)),true);}foreach(var directory in Directory.EnumerateDirectories(source))CopyDirectory(directory,Path.Combine(destination,Path.GetFileName(directory)),token);}
    private static (long Bytes,long Files) TreeSize(string path){long bytes=0,files=0;foreach(var file in Directory.EnumerateFiles(path,"*",SearchOption.AllDirectories)){var info=new FileInfo(file);bytes+=info.Length;files++;}return(bytes,files);}
}
