using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Xml.Linq;
using ArchiveMail.Api.Gmail;
using ArchiveMail.Api.Infrastructure;
using Microsoft.AspNetCore.DataProtection;
using Npgsql;

namespace ArchiveMail.Api.Calendar;

public sealed class CalendarService(NpgsqlDataSource database,GmailService gmail,IHttpClientFactory clients,ActiveDatabaseConfiguration active)
{
    private const string GoogleApi="https://www.googleapis.com/calendar/v3";
    private readonly IDataProtector protector=DataProtectionProvider.Create(new DirectoryInfo(Path.Combine(active.DataDirectory,"data-protection-keys")),options=>options.SetApplicationName("ArchiveMail.AppSettings.v1")).CreateProtector("calendar-secrets");
    public async Task<IReadOnlyList<object>> AccountsAsync(CancellationToken token){await using var command=database.CreateCommand("SELECT id,provider,label,username,server_url,status,last_error,created_at,updated_at FROM calendar_accounts ORDER BY created_at DESC");await using var r=await command.ExecuteReaderAsync(token);var list=new List<object>();while(await r.ReadAsync(token))list.Add(new{id=r.GetString(0),provider=r.GetString(1),label=r.GetString(2),username=r.GetString(3),serverUrl=r.GetString(4),status=r.GetString(5),lastError=r.IsDBNull(6)?null:r.GetString(6),createdAt=r.GetString(7),updatedAt=r.GetString(8)});return list;}
    public async Task<object> AddAppleAsync(JsonElement input,CancellationToken token){var server=Required(input,"serverUrl").TrimEnd('/');var username=Required(input,"username");var password=Required(input,"appSpecificPassword");await AppleRequest(server,username,password,new HttpMethod("PROPFIND"),"<d:propfind xmlns:d=\"DAV:\"><d:prop><d:displayname/></d:prop></d:propfind>","0",token);var id=Guid.NewGuid().ToString();var now=DateTimeOffset.UtcNow.ToString("O");await using var command=database.CreateCommand("INSERT INTO calendar_accounts(id,provider,label,username,server_url,secret,status,created_at,updated_at) VALUES($1,'apple',$2,$3,$4,$5,'connected',$6,$6)");command.Parameters.AddWithValue(id);command.Parameters.AddWithValue(Required(input,"label"));command.Parameters.AddWithValue(username);command.Parameters.AddWithValue(server);command.Parameters.AddWithValue(protector.Protect(password));command.Parameters.AddWithValue(now);await command.ExecuteNonQueryAsync(token);return(await AccountsAsync(token)).Single(item=>Property(item,"id")==id);}
    public async Task DeleteAccountAsync(string id,CancellationToken token){await using var command=database.CreateCommand("DELETE FROM calendar_accounts WHERE id=$1");command.Parameters.AddWithValue(id);await command.ExecuteNonQueryAsync(token);}
    public async Task<IReadOnlyList<object>> SourcesAsync(string owner,CancellationToken token){var list=new List<object>();foreach(var connection in await gmail.ListAsync(owner,token)){if(!connection.CanManageCalendar)continue;try{var json=await gmail.GoogleRequestAsync(connection.Id,owner,$"{GoogleApi}/users/me/calendarList?minAccessRole=reader",HttpMethod.Get,null,token);if(json.TryGetProperty("items",out var items))foreach(var item in items.EnumerateArray()){var external=item.GetProperty("id").GetString()!;list.Add(new{id=$"google:{connection.Id}:{Base64(external)}",provider="google",accountId=connection.Id,accountLabel=connection.Email,externalId=external,name=Text(item,"summary")??external,color=Text(item,"backgroundColor")??"#4285f4",readOnly=Text(item,"accessRole")=="reader",primary=item.TryGetProperty("primary",out var primary)&&primary.GetBoolean(),selectedByDefault=!item.TryGetProperty("selected",out var selected)||selected.GetBoolean()});}}catch(InvalidOperationException){}}
        foreach(var account in await AppleRecords(token))list.Add(new{id=$"apple:{account.Id}",provider="apple",accountId=account.Id,accountLabel=account.Label,externalId=account.Server,name=account.Label,color="#ff3b30",readOnly=false,primary=true,selectedByDefault=true});return list;}
    public Task<IReadOnlyList<object>> GoogleEvents(string connection,string min,string max,string owner,CancellationToken token)=>GoogleCalendarEvents(connection,"primary",min,max,owner,token);
    public async Task<IReadOnlyList<object>> SourceEvents(string source,string min,string max,string owner,CancellationToken token){var parsed=await ResolveSource(source,owner,token);return parsed.Provider=="google"?await GoogleCalendarEvents(parsed.AccountId,parsed.External,min,max,owner,token):await AppleEvents(parsed.AccountId,min,max,token);}
    public Task<object> CreateGoogle(string connection,JsonElement input,string owner,CancellationToken token)=>GoogleWrite(connection,"primary",null,input,owner,HttpMethod.Post,token);
    public async Task<object> CreateFromMessage(string messageId,string connection,JsonElement input,string owner,CancellationToken token)
    {
        await using(var owns=database.CreateCommand("SELECT EXISTS(SELECT 1 FROM messages m JOIN archives a ON a.id=m.archive_id WHERE m.id=$1 AND a.owner_user_id=$2)"))
        {
            owns.Parameters.AddWithValue(messageId);owns.Parameters.AddWithValue(owner);
            if(!Convert.ToBoolean(await owns.ExecuteScalarAsync(token)))throw new KeyNotFoundException("Message not found");
        }
        var result=await CreateGoogle(connection,input,owner,token);
        var value=JsonSerializer.SerializeToElement(result);
        var id=Required(value,"id");var title=Required(value,"title");var start=Required(value,"startAt");
        await using var link=database.CreateCommand("INSERT INTO message_calendar_events(message_id,connection_id,event_id,title,start_at,created_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(connection_id,event_id) DO UPDATE SET message_id=EXCLUDED.message_id,title=EXCLUDED.title,start_at=EXCLUDED.start_at");
        link.Parameters.AddWithValue(messageId);link.Parameters.AddWithValue(connection);link.Parameters.AddWithValue(id);link.Parameters.AddWithValue(title);link.Parameters.AddWithValue(start);link.Parameters.AddWithValue(DateTimeOffset.UtcNow.ToString("O"));
        await link.ExecuteNonQueryAsync(token);return result;
    }
    public Task<object> UpdateGoogle(string connection,string eventId,JsonElement input,string owner,CancellationToken token)=>GoogleWrite(connection,"primary",eventId,input,owner,HttpMethod.Put,token);
    public async Task DeleteGoogle(string connection,string eventId,string owner,CancellationToken token)=>_ = await gmail.GoogleRequestAsync(connection,owner,$"{GoogleApi}/calendars/primary/events/{Uri.EscapeDataString(eventId)}",HttpMethod.Delete,null,token);
    public async Task<object> CreateSource(string source,JsonElement input,string owner,CancellationToken token){var parsed=await ResolveSource(source,owner,token);return parsed.Provider=="google"?await GoogleWrite(parsed.AccountId,parsed.External,null,input,owner,HttpMethod.Post,token):await AppleWrite(parsed.AccountId,null,input,token);}
    public async Task<object> UpdateSource(string source,string eventId,JsonElement input,string owner,CancellationToken token){var parsed=await ResolveSource(source,owner,token);return parsed.Provider=="google"?await GoogleWrite(parsed.AccountId,parsed.External,eventId,input,owner,HttpMethod.Put,token):await AppleWrite(parsed.AccountId,eventId,input,token);}
    public async Task DeleteSource(string source,string eventId,string owner,CancellationToken token){var parsed=await ResolveSource(source,owner,token);if(parsed.Provider=="google")await DeleteGoogleCalendar(parsed.AccountId,parsed.External,eventId,owner,token);else{var account=(await AppleRecords(token)).Single(item=>item.Id==parsed.AccountId);await AppleRequest($"{account.Server.TrimEnd('/')}/{Uri.EscapeDataString(eventId)}.ics",account.Username,protector.Unprotect(account.Secret),HttpMethod.Delete,null,null,token);}}
    private async Task<IReadOnlyList<object>> GoogleCalendarEvents(string connection,string calendar,string min,string max,string owner,CancellationToken token){var url=$"{GoogleApi}/calendars/{Uri.EscapeDataString(calendar)}/events?singleEvents=true&orderBy=startTime&timeMin={Uri.EscapeDataString(min)}&timeMax={Uri.EscapeDataString(max)}&maxResults=2500";var json=await gmail.GoogleRequestAsync(connection,owner,url,HttpMethod.Get,null,token);var list=new List<object>();if(json.TryGetProperty("items",out var items))foreach(var item in items.EnumerateArray())list.Add(MapGoogle(item,connection));return list;}
    private async Task<object> GoogleWrite(string connection,string calendar,string? eventId,JsonElement input,string owner,HttpMethod method,CancellationToken token){var payload=JsonSerializer.SerializeToElement(new{summary=Required(input,"title"),description=String(input,"description")??"",location=String(input,"location")??"",start=GoogleTime(input,"startAt",Boolean(input,"allDay")),end=GoogleTime(input,"endAt",Boolean(input,"allDay"))});var url=$"{GoogleApi}/calendars/{Uri.EscapeDataString(calendar)}/events"+(eventId is null?"":$"/{Uri.EscapeDataString(eventId)}");return MapGoogle(await gmail.GoogleRequestAsync(connection,owner,url,method,payload,token),connection);}
    private async Task DeleteGoogleCalendar(string connection,string calendar,string eventId,string owner,CancellationToken token)=>_ = await gmail.GoogleRequestAsync(connection,owner,$"{GoogleApi}/calendars/{Uri.EscapeDataString(calendar)}/events/{Uri.EscapeDataString(eventId)}",HttpMethod.Delete,null,token);
    private static object MapGoogle(JsonElement item,string connection){var start=item.GetProperty("start");var end=item.GetProperty("end");var allDay=start.TryGetProperty("date",out _);return new{id=Text(item,"id")??"",connectionId=connection,provider="google",title=Text(item,"summary")??"(Untitled)",description=Text(item,"description")??"",location=Text(item,"location")??"",startAt=Text(start,allDay?"date":"dateTime")??"",endAt=Text(end,allDay?"date":"dateTime")??"",allDay,htmlLink=Text(item,"htmlLink"),meetingLink=Text(item,"hangoutLink"),organizer=item.TryGetProperty("organizer",out var organizer)?new{email=Text(organizer,"email")??"",displayName=Text(organizer,"displayName")} : null,attendees=item.TryGetProperty("attendees",out var attendees)?attendees.EnumerateArray().Select(value=>new{email=Text(value,"email")??"",displayName=Text(value,"displayName"),responseStatus=Text(value,"responseStatus")??"needsAction",organizer=value.TryGetProperty("organizer",out var o)&&o.GetBoolean(),self=value.TryGetProperty("self",out var s)&&s.GetBoolean()}).ToArray():System.Array.Empty<object>()};}
    private async Task<IReadOnlyList<object>> AppleEvents(string accountId,string min,string max,CancellationToken token){var account=(await AppleRecords(token)).Single(item=>item.Id==accountId);var start=DateTimeOffset.Parse(min).UtcDateTime.ToString("yyyyMMdd'T'HHmmss'Z'");var end=DateTimeOffset.Parse(max).UtcDateTime.ToString("yyyyMMdd'T'HHmmss'Z'");var report=$"<c:calendar-query xmlns:d=\"DAV:\" xmlns:c=\"urn:ietf:params:xml:ns:caldav\"><d:prop><d:getetag/><c:calendar-data/></d:prop><c:filter><c:comp-filter name=\"VCALENDAR\"><c:comp-filter name=\"VEVENT\"><c:time-range start=\"{start}\" end=\"{end}\"/></c:comp-filter></c:comp-filter></c:filter></c:calendar-query>";var text=await AppleRequest(account.Server,account.Username,protector.Unprotect(account.Secret),new HttpMethod("REPORT"),report,"1",token);var doc=XDocument.Parse(text);XNamespace cal="urn:ietf:params:xml:ns:caldav";var list=new List<object>();foreach(var data in doc.Descendants(cal+"calendar-data")){var parsed=ParseIcs(data.Value,accountId);if(parsed is not null)list.Add(parsed);}return list;}
    private async Task<object> AppleWrite(string accountId,string? eventId,JsonElement input,CancellationToken token){var account=(await AppleRecords(token)).Single(item=>item.Id==accountId);var id=eventId??Guid.NewGuid().ToString();var allDay=Boolean(input,"allDay");var start=IcsTime(Required(input,"startAt"),allDay);var end=IcsTime(Required(input,"endAt"),allDay);var ics=$"BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Archive Mail//EN\r\nBEGIN:VEVENT\r\nUID:{EscapeIcs(id)}\r\nDTSTAMP:{DateTime.UtcNow:yyyyMMdd'T'HHmmss'Z'}\r\nDTSTART{(allDay?";VALUE=DATE":"")}:{start}\r\nDTEND{(allDay?";VALUE=DATE":"")}:{end}\r\nSUMMARY:{EscapeIcs(Required(input,"title"))}\r\nDESCRIPTION:{EscapeIcs(String(input,"description")??"")}\r\nLOCATION:{EscapeIcs(String(input,"location")??"")}\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n";await AppleRequest($"{account.Server.TrimEnd('/')}/{Uri.EscapeDataString(id)}.ics",account.Username,protector.Unprotect(account.Secret),HttpMethod.Put,ics,null,token,"text/calendar; charset=utf-8");return ParseIcs(ics,accountId)!;}
    private async Task<(string Provider,string AccountId,string External)> ResolveSource(string source,string owner,CancellationToken token){if(source.StartsWith("apple:")){var id=source[6..];if(!(await AppleRecords(token)).Any(value=>value.Id==id))throw new KeyNotFoundException("Calendar source not found");return("apple",id,id);}if(source.StartsWith("google:")){var parts=source.Split(':',3);if(parts.Length!=3||(await gmail.ListAsync(owner,token)).All(value=>value.Id!=parts[1]))throw new KeyNotFoundException("Calendar source not found");return("google",parts[1],Unbase64(parts[2]));}throw new KeyNotFoundException("Calendar source not found");}
    private async Task<IReadOnlyList<AppleRecord>> AppleRecords(CancellationToken token){await using var command=database.CreateCommand("SELECT id,label,username,server_url,secret FROM calendar_accounts WHERE provider='apple'");await using var r=await command.ExecuteReaderAsync(token);var list=new List<AppleRecord>();while(await r.ReadAsync(token))list.Add(new(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4)));return list;}
    private async Task<string> AppleRequest(string url,string username,string password,HttpMethod method,string? body,string? depth,CancellationToken token,string contentType="application/xml; charset=utf-8"){using var request=new HttpRequestMessage(method,url);request.Headers.Authorization=new AuthenticationHeaderValue("Basic",Convert.ToBase64String(Encoding.UTF8.GetBytes($"{username}:{password}")));if(depth is not null)request.Headers.TryAddWithoutValidation("Depth",depth);if(body is not null)request.Content=new StringContent(body,Encoding.UTF8,contentType.Split(';')[0]);using var response=await clients.CreateClient("external").SendAsync(request,token);var text=await response.Content.ReadAsStringAsync(token);if(!response.IsSuccessStatusCode)throw new InvalidOperationException($"Apple Calendar returned {(int)response.StatusCode}: {text[..Math.Min(300,text.Length)]}");return text;}
    private static object? ParseIcs(string text,string account){var lines=text.Replace("\r\n ","").Split(new[]{"\r\n","\n"},StringSplitOptions.None);string? Value(string key)=>lines.FirstOrDefault(line=>line.StartsWith(key,StringComparison.OrdinalIgnoreCase))?.Split(':',2).ElementAtOrDefault(1);var id=Value("UID");var startLine=lines.FirstOrDefault(line=>line.StartsWith("DTSTART",StringComparison.OrdinalIgnoreCase));var endLine=lines.FirstOrDefault(line=>line.StartsWith("DTEND",StringComparison.OrdinalIgnoreCase));if(id is null||startLine is null||endLine is null)return null;var allDay=startLine.Contains("VALUE=DATE");var start=ParseIcsTime(startLine.Split(':',2)[1],allDay);var end=ParseIcsTime(endLine.Split(':',2)[1],allDay);return new{id,connectionId=account,sourceId=$"apple:{account}",provider="apple",title=UnescapeIcs(Value("SUMMARY")??"(Untitled)"),description=UnescapeIcs(Value("DESCRIPTION")??""),location=UnescapeIcs(Value("LOCATION")??""),startAt=start,endAt=end,allDay,htmlLink=(string?)null,meetingLink=(string?)null,organizer=(object?)null,attendees=System.Array.Empty<object>()};}
    private static object GoogleTime(JsonElement input,string name,bool allDay)=>allDay?new{date=DateTimeOffset.Parse(Required(input,name)).ToString("yyyy-MM-dd")}:(object)new{dateTime=DateTimeOffset.Parse(Required(input,name)).ToString("O")};
    private static string IcsTime(string value,bool allDay)=>allDay?DateTimeOffset.Parse(value).ToString("yyyyMMdd"):DateTimeOffset.Parse(value).UtcDateTime.ToString("yyyyMMdd'T'HHmmss'Z'");
    private static string ParseIcsTime(string value,bool allDay)=>allDay?DateTime.ParseExact(value,"yyyyMMdd",null).ToString("yyyy-MM-dd"):DateTime.SpecifyKind(DateTime.ParseExact(value.TrimEnd('Z'),"yyyyMMdd'T'HHmmss",null),DateTimeKind.Utc).ToString("O");
    private static string EscapeIcs(string value)=>value.Replace("\\","\\\\").Replace("\r","").Replace("\n","\\n").Replace(",","\\,").Replace(";","\\;");private static string UnescapeIcs(string value)=>value.Replace("\\n","\n").Replace("\\,",",").Replace("\\;",";").Replace("\\\\","\\");
    private static string Base64(string value)=>Convert.ToBase64String(Encoding.UTF8.GetBytes(value)).TrimEnd('=').Replace('+','-').Replace('/','_');private static string Unbase64(string value){var normalized=value.Replace('-','+').Replace('_','/');normalized+=new string('=',(4-normalized.Length%4)%4);return Encoding.UTF8.GetString(Convert.FromBase64String(normalized));}
    private static string? Property(object value,string name)=>value.GetType().GetProperty(name)?.GetValue(value)?.ToString();private static string? Text(JsonElement input,string name)=>input.ValueKind==JsonValueKind.Object&&input.TryGetProperty(name,out var value)&&value.ValueKind==JsonValueKind.String?value.GetString():null;private static string? String(JsonElement input,string name)=>Text(input,name)?.Trim();private static string Required(JsonElement input,string name)=>String(input,name)??throw new ArgumentException($"{name} is required");private static bool Boolean(JsonElement input,string name)=>input.TryGetProperty(name,out var value)&&value.ValueKind==JsonValueKind.True;
    private sealed record AppleRecord(string Id,string Label,string Username,string Server,string Secret);
}
